### ISSUE TITLE
Email settings not being saved

### ISSUE THREAD

**Issue by pweaver2019** [FalconChristmas/fpp#1057]
When using an email server within my network I set;

```
SMTP Server Hostname: smtp.mydomain.com
SMTP Server Port: 25
SMTP Server Login:
SMTP Server Password:
From Email Address: fpp001@mydomain.com
From Name: fpp001
Default TO Address: me@mydomaiin.com

```

In www/common.php there is an if that says;
```
    if (($emailuser == '') ||
        ($emailpass == '') ||
        ($emailtoemail == '')) {
        return;
    }
```

In my example emailuser and emailpass are both blank so this if does a return and does not reach the section where the conf file is written.  I removed those 5 lines from common.php and that resolved the issue for me. I **think** that removing the if is the correct way to go. Maybe a better answer is to change the || to &, (in my example that would have solved it too) but I think the code should not be returning at that point since the user might be erasing a previous setup.

**Comment by patdelaney** [comment]
I don't understand the issue?  I created email settings with a user and password and it saved, and I created on a different fpp settings with no user and password and they both saved.

**Comment by pweaver2019** [comment]
You are probably looking at /home/fpp/media/settings. Yes, the values are stored in /home/fpp/media/settings. But after that "if" I mentioned in www.common.php there is code that writes the data to /etc/exim4/update-exim4.conf.conf and then does exec("sudo update-exim4.conf") to process that data. If the user or pass or toemail is not defined then the code never writes out the conf file and never runs the update-exim4.conf. So if you try to send email on that fpp with no user the default will send to smtp.gmail.com, not the sever you defined.

**Comment by patdelaney** [comment]
Ok that is clearer.
Do you have an example of the script you are using to send mail or just
using the Test button?

**Comment by pweaver2019** [comment]
You're right, now that I look at the subject I realize that it was misleading.
I'm just using the Test button, when the message bounced back I saw that the bounce came from smtp.gmail.com.

**Comment by Poporacer** [comment]
Are you setting your email settings through the UI and not through the shell?

**Comment by pweaver2019** [comment]
I'm setting the email through the UI, not through the shell. Removing that "if" statement I mentioned above in common.php fixes the issue.

**Comment by jaredb7** [comment]
Yeah so what pweaver2019 is doing is running a internal mail server that doesn't require a username and password for authentication (I personally wouldn't do this but that's just me).

When we were just using Gmail you always required both anyway because there was no way email would work without. so there is IF statement that prevents the rest of the code generating the relevant exim4 config.
But I guess now since you can use whatever service, there may be case where either of these are missing

we would need to do is just adjust the statement to return if the "To Email" is empty as that's still a requirement to get the mail to the correct place and missing this would generate a bad config. At least seeing that the username and or password can both be empty depending on the users service/setup, To email is still required
