### ISSUE TITLE
Add traceroute to BBB Images

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#1066]
**Is your feature request related to a problem? Please describe.**
Not directly.

**Describe the solution you'd like**
When troubleshooting an end users routing issue on a BBB and needed traceroute (or one of the variants) and noticed it wasn't installed.  Verified that it is installed on a Pi running the same image (both on 5.0.1).

**Describe alternatives you've considered**
Installing it myself but no access to the internet makes it challenging to walk a user through.

**Additional context**
None

**Comment by darylc** [comment]
The last few times I tried to add a new package to the base FPP install, I was told that non essential packages are being left out of the base FPP images especially on Beaglebone's so that FPP can continue to fit on the emmc.  I'd suggest that the need for traceroute these days when most end-users tend to use proxies rather than routing for complex setups, the need for traceroute is reduced.
