### ISSUE TITLE
FPP Backup and Restore does not include eth1 configuration (USB Ethernet Dongle)

### ISSUE THREAD

**Issue by LiteSho** [FalconChristmas/fpp#1077]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 5.1 running on RPi 3b

**Describe the bug and Steps to reproduce**: 
I saved all config settings from FPP v4.2 to a JSON file.  After flashing a new micro SD card with the FPP v5.1 image for Pi, and restored the config settings from FPP v4.2, the eth1 interface settings from v4.2 did not carry over to v5.1.  The eth1 interface is associated with a gigabit USB adapter that I've used with all previous versions of FPP on the Pi.  After restoring, it is supposed to restore a static IP address.  The eth0 settings restored properly (static IP), however, eth1 did not and was blank, set for DHCP.

**Expected behavior**: 
Upon a full restore (including network settings), I expected all network interface configurations to be restored.  Both eth0 (built-in) and eth1 (USB) were set with static IP address network configuration.  However, only eth0 was restored properly with a static IP.

**Additional context**: 
N/A

**Additional Attachments**
N/A

**Comment by jaredb7** [comment]
Hi @LiteSho, apologies for this issue, The eth1 settings didn't restore due to not being backed up at all. This was due to a slight oversight on what interfaces would be used back when it was created.

The backup system has been updated to pull in all interface configurations it finds, not just eth0 and wlan0.
Not sure what version my change will make it to (maybe 5.3?), but currently in master if you do a backup, static settings for eth1 (or whatever it may be) will be backed up.
