### ISSUE TITLE
Please add ability to download FPPOS images from GitHub to the File Manager.

### ISSUE THREAD

**Issue by neowolfwitch** [FalconChristmas/fpp#1097]
**Is your feature request related to a problem? Please describe.**
Nope. Just a feature request.
I really love that you added the ability to download FPPOS files to the Help -> About menu, but it only allows you to download the file for your platform (PI vs BBB). Many (most?) of us have mixed environments with several FPP boxes running, and do almost everything through MultiSync. 

I definitely understand why you wouldn't want to make a BBB fppos image available on a Pi upgrade screen. That would be really-really confusing.

**Describe the solution you'd like**
FPPOS images are kept in the "Uploads" section of file manager, where they can be distributed to other FPP installs for upgrade. It would be great if there was an option here to download these directly from GitHub, similar to the option in Help -> About, but allow any platform to be downloaded (Pi vs. BBB).

**Describe alternatives you've considered**
Right now I can, and do, download these on my computer, and then upload them to my FPP "Master" manually. This would just save a couple of steps and some download/upload time, and keep everything in FPP.

**Comment by ghormann** [comment]
Second time this has come up.... Still working on the complete design, but I *think* it will be Multisync instead of About or File Manager.  The idea is basically this
1) Replace the current ability of the Multisync page where it can "push" FPPOS files to other devices.   Make it so that you select releases instead of a specific file.   
2) Based on uniquely selected devices, it will download the required images from Github if they don't already exists. 
3) Once downloaded it will push the correct FPPOS files to the correct devices based on their target architecture
4) Once the file has been pushed, there is an "optional" checkbox that will also start the upgrade process on the remote.   

Input from those with a lot of devices on this kind of design would be greatly appreciated.

**Comment by neowolfwitch** [comment]
Sorry, if this is a dupe. I didn't see it.

I did notice there isn't a way to actually load the new fppos image in MultiSync, so...

That's awesome news! Thank you!

Wolf

**Comment by patdelaney** [comment]
As ling as this doesn't depend on a device having to be in "master" mode. I have many stand alone devices in the lab that are not part of a master/remote configuration.

**Comment by ghormann** [comment]
@patdelaney with this new design mode (player vs remote) would NOT be a fector.  Whichever device you're logging into would have to have 
1. access to GitHub (internet access)
2. enough diskspace for the food images
3. The ability to reach all the other fpp instances.

**Comment by cpinkham** [comment]
I'd like to eventually install and configure automount in FPP which would allow FPP instances to upgrade via a .fppos image stored on another system.  In this scenario, you would only need to download once to once system and then could upgrade the rest from the .fppos file stored on the first one.

**Comment by darylc** [comment]
The FPP developers discussed this issue and decided that a way to be able to download fppos images for other platforms should be added.  I am about to commit this functionality to the about page with a checkbox to show all platforms.  This will be available in advanced mode.

**Comment by darylc** [comment]
![image](https://user-images.githubusercontent.com/7511887/216809367-cda1c2c6-9eba-40d4-85ff-322025980af0.png)
