### ISSUE TITLE
Brackets in Audio Filename Prevents Scheduele from Playing

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#1112]
**FPP Version and Hardware**: 
FPP 5.2
xLights 2021.31
Pi 3B+

**Describe the bug and Steps to reproduce**: 
Observed in the xLights zoom room on different users computer.

FSEQ Name: "The Devil Went Down to Georgia.fseq"
MP3 Name: "The Devil Went Down to Georgia [Edited].mp3"

The playlist was created using the filenames above.  The files were uploaded with fpp connect.

The issue is that the status page shows that the fseq & audio was playing (timer decrementing) however no data was being sent to controllers.

To isolate the issue we went to testing in FPP and played just the FSEQ page and it worked fine.

Perminant fix (yea, some steps could be skipped)
* Rename MP3 on his computer
* Fix sequence to refrence the renamed mp3
* Tools > Fpp connect ... upload
* Updated the playlist

I don't have the log files as this was on a 3rd party's computer but should be easily reproducible by a developer.

This is a follow-up to https://github.com/smeighan/xLights/issues/2829

**Comment by ghormann** [comment]
I believe the playlist part was fixed with 807a5cb6c49ccea4116db953412329562e30f19d.   The SaveSequence API now sanitizes the filenames in the same way that is done via the file upload API. 

There is still a problem with playing a sequence (not the playlist) when the sequence has special characters.  The media name in the .fseq file is not cleansed.     I'll push a fix for this shortly.
