### ISSUE TITLE
add playlist download/delete to file manager

### ISSUE THREAD

**Issue by Tom-Neverwinter** [FalconChristmas/fpp#1134]
**Is your feature request related to a problem? Please describe.**

corrupted playlist damaged ability to even access the playlist page, however all playlists were not damaged or changed. 
a separate bug enabled me to nuke the troubled playlist. 

https://github.com/FalconChristmas/fpp/issues/1113#issuecomment-952365737

This also exposed a want to have the ability to backup playlists easily. [may also apply to schedules?]

**Describe the solution you'd like**

delete and download playlists from file manager.

**Describe alternatives you've considered**

I was attempting to perform this action through xlights. with the current space bug I was able to delete the corrupted playlist. 

**Additional context**

**Comment by cpinkham** [comment]
You should be able to browse to the "FPP" share from your computer and go to the playlists directory and delete a playlist if absolutely necessary.  I could see us adding a way to delete a playlist from the main playlist editor UI by clicking a trashcan icon or something, but I don't know that we would add this ability to the file manager which is for user-managed files, not files FPP is managing.

Keeping the ticket open for now since it could be an enhancement to delete a playlist from the playlist list UI without going into the playlist editor to delete the playlist you are editing.
