### ISSUE TITLE
Add WLED effects to Status Control/Effects page

### ISSUE THREAD

**Issue by cjalmond** [FalconChristmas/fpp#1137]
**Is your feature request related to a problem? Please describe.**
I believe this would make it far easier to play the WLED effects.

**Describe the solution you'd like**
Instead of WLED effects being in FPP Command editor and then overlay model effect putting them a few clicks away from execution is a better UX.

**Comment by cpinkham** [comment]
I think that we have 3 different options for doing this different ways already so don't know that we need another way to turn on/off these effects.  We already have the BigButtons plugin which gives one-click/touch access to running FPP Commands which can turn effects on and off.  You can also make Command Presets and trigger those directly from the Command Presets editor page.  I also just committed an enhancement to the popup 'Run FPP Command' window that allows you to select (and optionally edit or edit-and-save) a Command Preset and run it directly rather than having to configure a new command on the fly.  The changes also allow you to keep the window open so you can tweak the settings for an effect and re-start the effect without having to close/re-open the window.
