### ISSUE TITLE
Add STOP button to correspond with the PLAY button on File Manager Sequences tab

### ISSUE THREAD

**Issue by MarkA75160** [FalconChristmas/fpp#1189]
**Is your feature request related to a problem? Please describe.**
In the File Manager Sequences tab, there is a PLAY button to manually start a sequence.  However there is no corresponding STOP button and the user must wait for the sequence to play through to the end (or restart FPPD)

**Describe the solution you'd like**
Add a STOP button to stop a manually started sequence

**Describe alternatives you've considered**
restarting fppd works, but is less undesirable.

**Additional context**
Add STOP button in this section
![image](https://user-images.githubusercontent.com/57245161/145232462-36a7562f-3c6e-44c6-ac38-3cc47ae7203a.png).

**Comment by darylc** [comment]
I guess things have changed since 2021, if you play a sequence from that page now, it automatically redirects you to the main status page of fpp and the sequence starts playing.  At that point you have a big stop button right there, so no need for a stop button in the filemanager.
![image](https://user-images.githubusercontent.com/7511887/214793364-8b1ce8c8-ea68-4b9c-bee7-cd95708d861a.png)

**Comment by MarkA75160** [comment]
Agreed.   This is a non-issue with the updated UI and ok to be closed
