### ISSUE TITLE
BBB: ETH1 ip address not displayed on hdmi output after boot up

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#119]
If I have a USB Ethernet adapter connected to the BBB, after it reboots, the system announces all 3 ip's (eth0, eth1 ,and the usb0)

But the UI on the hdmi port only shows:
The IP Address for eth0 is:  192.168.1.110
The IP Address for usb0 is:  192.168.7.2

Just an fyi

**Comment by cpinkham** [comment]
I don't think this is coming from FPP, we don't print any messages like that.  We run "hostname -I" to get the list of IPs and echo the whole list in a format like "FPP - Found IP(s): IP1, IP2, IP3".  I think this is a stock debian script somewhere that is doing this, perhaps because eth1 is not configured in /etc/network/interfaces.    I'm not opposed to adding a fix, but it would be low priority to track down since I don't think it is in FPP code.
