### ISSUE TITLE
Time with seconds only on status page

### ISSUE THREAD

**Issue by nmiller0113** [FalconChristmas/fpp#1193]
**Is your feature request related to a problem? Please describe.**
I'm not sure whether this is a bug or intentional, which is why I opened this as a feature, but the time with seconds (HH:MM:SS) only shows on the status page. All of the other pages only show hours and minutes (HH:MM).

<img width="139" alt="Screen Shot 2021-12-09 at 11 25 55 AM" src="https://user-images.githubusercontent.com/1048868/145463508-341e841c-a051-4c3a-8414-fbb9cb2c5819.png">

**Describe the solution you'd like**
It would be great if it showed the seconds on all the pages (HH:MM:SS).

**Describe alternatives you've considered**
None other than looking at my computer clock :)

**Comment by cpinkham** [comment]
This is intentional.  The only place that seconds really matter is on the status page and we didn't want to have to have every single page refresh the status every second just to display the seconds at the top of each page.  The time is coming from the FPP instance, not from the local system, if it were coming from the local system we'd display seconds everywhere.
