### ISSUE TITLE
Other Outputs not calculating Channel Count

### ISSUE THREAD

**Issue by datcomputerguy** [FalconChristmas/fpp#1220]
**FPP Version and Hardware**: FPP v5.4.10 (v5.4 branch) BBB, RPi2, RPi3

**Describe the bug and Steps to reproduce**: 
1. Input/Output Setup --> Output channels --> Other
3. I have a VirtualMatrix that works defined.  Start Channel 500676 and the Channel Count is greyed out with 208200.  Width: 347, Height: 200 the rest doesn't matter.  This works fine.
4. If I go to add another output say HTTPVirtualDisplay, --> + Add --> HTTPVirtualDisplay.  I wanted to make a mirror HTTPVirtualDisplay of the actual VirtualMatrix.
5. When it shows the default row it has a default of Start: 1 and Channel Count 8388608.  If I change the width and heights it does not change the Channel Count. 
6. The channel count is locked out and cannot be edited.  Eventually after you click on things including save and bouncing between tabs (honestly not sure the pattern) The Channel Count box became editable and I was able to put in the channel count to match the virtualmatrix.  It seems like the UI is pulling in the max default value and locking it and/or not calculating when the height and width are changed.

**Expected behavior**: 
I expect to be able to change the channel count or have the channel count calculate correctly based on the width and height parameters.

**Additional context**: 
The HTTPVirtualDisplay does not seem to work when I go to Status/Control --> Virtual Display.  Not sure if the UI settings are not right and are causing it not to function or what....  There is a js console error:
![image](https://user-images.githubusercontent.com/3844234/147121116-aa496659-d1a0-4819-a476-68c96d165b9e.png)

**Additional Attachments**
I did not have any logs that would be appropriate to this bug, but please let me know if you need anything.

I pressed add to add the httpvirtualdisplay
![image](https://user-images.githubusercontent.com/3844234/147119737-62ffb16d-6c4b-4e6b-8a0b-81eef88b9824.png)
I changed the values to match the virtual matrix, I pressed save and got an error
![image](https://user-images.githubusercontent.com/3844234/147119785-7a62c6dd-9277-4602-8722-ef78c20f66ea.png)
I changed the start back to 1 and then the size to anything small like 10x10 and it let me press save
![image](https://user-images.githubusercontent.com/3844234/147119851-ed48f04f-f101-4077-a78b-7cf5f09eee45.png)
Once I hit save with channel start 1 and width/height:10 the channel count box became active:
![image](https://user-images.githubusercontent.com/3844234/147119924-d8694b60-9b46-4424-81b9-331ef5791143.png)
Then I was able to edit the values to what I wanted and it accepted it when I hit save.
(this screencap below doesn't show the toast that says it successfully saved, but it did.
![image](https://user-images.githubusercontent.com/3844234/147120052-d2ecb241-addc-4ea7-adca-ca00a006606c.png)
After the reboot/restart the settings are there and it seems happy, but the virtual display doesn't seem to function (see additional context)

**Comment by cpinkham** [comment]
The Width and Height have nothing to do with the number of channels so this is why the channel count is not auto-calculated.  The Width and Height settings control the size of the preview image.  The Start Channel and Channel Count control which channel data is shown on the preview.  You can't draw the preview image showing only the virtual matrix, but you can set the channel settings so that only the virtual matrix channels are used in the preview.  The preview image itself will always show everything visible in your preview in xLights, but the size can be scaled using the Width/Height settings.

For the second issue of the HTTP Virtual Display not working, I think that may be because of your low odd-sized Width/Height values.  Try giving something more reasonable like 800x600 or 1024x576 and see if it works.

**Comment by datcomputerguy** [comment]
lol.  disregard it all then lol.  Thank you
