### ISSUE TITLE
FPP 5.4.1 Not receiving Sync Packets

### ISSUE THREAD

**Issue by TechplexEngineer** [FalconChristmas/fpp#1221]
May be related to #1192 

**FPP Version and Hardware**: 
FPP 4.5.1 running on BBB

**Describe the bug and Steps to reproduce**: 
When the show starts vua the playlist, sometimes it takes minutes or longer (sometimes never) for the remote controllers to get in sync with the master controller.
On a good day the multisync page looks like this will all of the devices in lockstep:
<img width="1340" alt="Screen Shot 2021-12-24 at 4 47 38 PM" src="https://user-images.githubusercontent.com/175873/147372903-d3e1af7a-68bf-4007-aac6-ade18b73375f.png">

Then sometimes a controller "falls off the wagon" and is idle when the others are playing.
<img width="1348" alt="Screen Shot 2021-12-24 at 4 48 53 PM" src="https://user-images.githubusercontent.com/175873/147372916-db06e8bb-1885-4023-ab98-461b837e286f.png">

Not sure on how to reproduce

**Expected behavior**: 
Controllers should stay in sync

**Additional Attachments**
logs from the "peacestakes" controller (RPI 4 with PiHat running FPP 5.4.1)
[FPP_Logs_20211224.2140.zip](https://github.com/FalconChristmas/fpp/files/7775162/FPP_Logs_20211224.2140.zip)

Logs from the "megatree" controller (BBB with FPP 5.4.1 Kulp Lights K16-B)
[FPP_Logs_20211224.2144-megatree.zip](https://github.com/FalconChristmas/fpp/files/7775166/FPP_Logs_20211224.2144-megatree.zip)

logs from the "master" controller (Pi4, soundblaster usb and sifm transmitter_
[FPP_Logs_20211224.2143-master.zip](https://github.com/FalconChristmas/fpp/files/7775164/FPP_Logs_20211224.2143-master.zip)

**Comment by libby2cm** [comment]
I had similar issues with my bb based controllers flaking out earlier in the season... dropping out, locking up, etc.. i made a few config changes on a hunch, and they have been stable for over a month now:

sys settings:
- status display: disabled

input/output settings:
- input control: disable network bridge monitoring
- default video output device: disabled

I suspect there is a thread being blocked or something screwy with the pru's, i'm sure dan will probably look at it next year, but the above does seem to be a work around for the studdering/freezing on the bb's.  Pi's have all been fine for me.

On a related note, I did not know the esp player code was a functional thing!  Need to check that out.

**Comment by dobletech** [comment]
I had a major problem with this last night, and tracked it down to my main Player (master) FPP having unchecked the "Send MultiSync Packets" on the FPP Settings...System tab. This was likely unintentionally done by me at some point (Occam's razor would say to blame human error) but I do not know that conclusively. So even though you may have your FPP set as "Player" you still need to tell it to send the MultiSync packets to the remotes because not every Player is in a multi-instance environment that would require the extra network traffic (no matter how small it is).
Good luck!
![FPP_Settings](https://user-images.githubusercontent.com/96639096/147375466-32fe1722-3c1a-4334-8dfa-598ec85fbd39.jpg)

**Comment by TechplexEngineer** [comment]
Thanks for the ideas @libby2cm and @dobletech 
Just double checked that "Send MultiSync Packets" is definitely enabled

I've checked "disable network bridge monitoring" in Status/Control > FPP Settings (Had to choose "Advanced" in UI > User Interface Level )

We'll see if disabling the network bridge monitoring makes a difference tonight. If not I'll try disabling video output. Hopefully we can narrow this down

**Comment by libby2cm** [comment]
@TechplexEngineer actually, i think your problem at hand may be simpler... on your master, open the multisync config page, then check the boxes next to the IP for each remote, then uncheck the 2 boxes on that same page (under settings) for multicast and broadcast.. by doing these steps, you enable unicast for the multisync traffic and are disabling multicast (default) and broadcast, which are frought with issues for a few reasons, and will kill that esp for sure.  Backup your config on your master first, but then make this change and I suspect you will be good tonight.  Don't worry about the other changes i mentioned yesterday for now.

![image](https://user-images.githubusercontent.com/6451331/147393838-498b1ff3-125e-49d7-a4ca-a49a530d8f2b.png)

**Comment by TechplexEngineer** [comment]
@libby2cm Wow not using multicast makes a big difference. The timing sync between the controllers is much better! Thanks!

**Comment by MarkA75160** [comment]
Multicast should not be used unless you have a network that fully supports it.  Most home networks with consumer-grade equipment don't have full multicast support (which would include a multicast router operating as an igmp querier).   Without a querier on the network, mulitcast subscriptions can expire which results in clients not receiving multicast packets. 

It appears that is what happened in this case, since Unicast fixed the issues.  I suspect using Broadcast would have also worked, but Unicast is often the better choice with less than a dozen or so remotes.

Closing this issue.   Feel free to reply and re-open if you know that you do have an IGMP Multicast Querier on your network which should have been keeping the subscriptions active.
