### ISSUE TITLE
Ability to stop a script / stop script when ran from playlist.

### ISSUE THREAD

**Issue by eatonaaron** [FalconChristmas/fpp#1258]
** Is your feature request related to a problem? Please describe. **
The issue we are seeing is when starting a script from the file explorer or script plugin, it cannot be stopped if it is one that runs infinitely/consecutively. For example, the clock script for led panels. when running this via the script explorer/file explorer and running it under a playlist, it cannot be cancelled/stopped.

**Describe the solution you'd like**
It would be great to have some sort of stop button or kill process/script button in the ui.
The best way to track that would be for the backend to track its process id, and then provide a stop button that would in the end kill that process/script off, and possibly restart fppd. Or find an option for the script to be killed off and for fppd to know that so fppd does not have to be restarted.

**Describe alternatives you've considered**
The workaround is to go into ssh/terminal, kill off the process, then restart FPPD.

**Additional context**
If there is a better way, let me know.  I have made a script that will auto kill the running script and restart fppd. but id love to not have to do that and just have a stop button like a playlist does.

**Comment by cpinkham** [comment]
This one is a bit hard to do completely.  We could try to track the PID of a spawn child process, but we have no idea if that child spawned other detached children, for instance if the script ran "nohup someOtherCommand &".  Traditionally, we have required stop versions of the start scripts because the person who wrote the start script is better suited to know how to stop the process than fppd just killing the child PID.

We can leave the ticket open for now, but I just wanted to point out that it won't solve all situations.  Doing this correctly will also require watching for children exiting and cleaning up the list as child processes die.

**Comment by darylc** [comment]
The FPP development team met and decided not to implement this as a feature.
