### ISSUE TITLE
Schedules to start more than 35 days out do not show up

### ISSUE THREAD

**Issue by almostengr** [FalconChristmas/fpp#1293]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 5.5 on Raspberry Pi 3

**Describe the bug and Steps to reproduce**: 
Via Web
* Go to Content Setup > Scheduler
* Create a schedule playlist that has a start date more than 35 days in the future and save.
* Check the Preview button in the upper left. 
* Schedule Preview modal will open and state that there is "Nothing Scheduled"

Via API
* Perform steps listed above first (Via Web)
* Using Postman or other API tool, make a GET request to http://<FPP Instance>/api/fppd/status
* In the "next_playlist" and "scheduler" parts of the response, you will see "No playlist scheduled" even though there is one or more scheduled in the future.

**Expected behavior**: 
After upgrading to version 5.5, schedules that are scheduled to start more than 35 days out from the current date do not show up in the Next Playlist via the API. Also schedules more than 35 days out should show up when clicking the Preview button on the Scheduler (Content Setup > Scheduler) screen. (see attached image)

**Additional context**: 
In version 4.6.1, schedules that have a start date beyond 35 days in the future would show up in the API as the next playlist.
This behavior should not have changed between versions. 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.
![Screenshot from 2022-06-19 08-21-09](https://user-images.githubusercontent.com/15150637/174483660-292ee2ce-9ac0-438a-a58b-edda1ee0e5bd.png)
![Screenshot from 2022-06-19 08-24-43](https://user-images.githubusercontent.com/15150637/174483661-bcf2419b-edb9-4cc4-9ea0-2eb5eaa3deb8.png)
[FPP_Logs_20220619.1332.zip](https://github.com/FalconChristmas/fpp/files/8935605/FPP_Logs_20220619.1332.zip)

**Comment by cpinkham** [comment]
For performance reasons, the scheduler only runs for about 5 weeks out into the future, so this is where you see 35 days sometimes.  This isn't likely to change with the current way the code works.  This is a big improvement, older versions of FPP only looked out into the future a maximum of one week, but I changed it to ~5 weeks when the scheduler was rewritten.  I have thought about making it a setting to allow the user to decide how far into the future to look for scheduled items.  I'm going to move this ticket to a FPP v6 feature request because it wouldn't take that long to add a new setting to make this configurable.

**Comment by cpinkham** [comment]
Setting added in 8914969c9a0
