### ISSUE TITLE
Pocketscroller continues to require an extra FPPD Restart after an update (v 6.0.2-5)

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#1337]
FPP Version: | 6.0.2-5-ge8c9caf2
Platform: | BeagleBone Black (PocketBeagle)
FPP OS Build: | v2022-07
OS Version: | Debian GNU/Linux 11 (bullseye)
Hardware Serial Number: | 1743GPB41992
Kernel Version: | 5.10.109-fpp
System Boot Time: | 2022-07-30 12:51:09
fppd Uptime: | 05:11
Local Git Version: | e8c9caf ChangeLog
Remote Git Version: | e8c9caf
[FPP_Logs_20220812.1330.zip](https://github.com/FalconChristmas/fpp/files/9316626/FPP_Logs_20220812.1330.zip)

Usually (but not every update), the 4 panel display on my Pocketscroller will light up 4 to 6 random pixels and is unresponsive to the playlist until I force an FPPD Restart. Then it is fine until the next update. This has been happening since an FPPOS update to version 6.0 but I ignored it.

**Comment by cpinkham** [comment]
The next time this happens, can you check the fppd.log file and see if it looks like fppd restarted properly during the update?  A couple years ago, we switched to doing a "fast" restart in most places.  Rather than issuing a fppd stop command and then a fppd start command, we instead tell fppd to restart itself and it respawns a new instance replacing the old instance.  This can be a bit quicker than the old stop/start method.  Maybe there is an issue with this quick restart that is worked around by using the normal stop/start as done via the UI when you click the button.

**Comment by JonB256** [comment]
Just did the update to v6.0.2-8 and it, of course, did not do it. The FPPD restart at the end was sufficient.
Will keep track of it after each update.
