### ISSUE TITLE
FPP AP not available after completing initial setup

### ISSUE THREAD

**Issue by ptr727** [FalconChristmas/fpp#1350]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
6.0.2 on K4-PB

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
- Write 6.0.2 to SD card using Balena etcher.
- Boot, complete initial setup, grow storage, reboot.
- After reboot FPP AP does not come back up.
- Oled displays configured hostname and IP, but no WiFi AP `FPP` SSID.
- Must rewrite SD, restart setup, and configure WiFi client mode before first reboot, if not configuring WiFi before reboot no AP mode.

**Expected behavior**: 
After initial setup, and grow storage, should be able to reboot before configuring network to switch to client mode.

**Additional context**: 
Using AC1200M USB WiFi bought from Kulp with K4-PB.

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by kas21** [comment]
I am also having this problem on my Kulp16

**Comment by darylc** [comment]
I can replicate the problem

**Comment by darylc** [comment]
Spent a lot of time on this one.  It's actually unrelated to the initial setup.  The FPP SSID will appear once only, if you power cycle it without going through the initial setup then it also disappears.

The root cause is a conflict between the mechanism to work out if to turn tethering on, and the old tethering config lying around on the previous boot.  It's some sort of boot order issue that is really tedious to track down (50+ reboots of a BBB aren't quick) and I can't quite get it.   Committing a workaround that should work well.  Workaround has been tested on PI  & BBB.
