### ISSUE TITLE
Minimum Version Pre Check in FPPOS File

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#1366]
**Is your feature request related to a problem? Please describe.**
See multiple times in the official zoom room (at least once daily) that end users are not upgrading their 5.x version before installing the FPPOS. 

**Describe the solution you'd like**
 Is it possible to include minimum version logic at the beginning of the FPPOS process to check that they are running a build that is supported.  

If that regex for that match isn't practical then check to see if some tools that are only in the newer version, lines of source, etc exist.

If the above check fails present the user with an error instructing them to upgrade to the current build of their branch and then retry the fppos.

**Comment by dkulp** [comment]
This cannot be done from anything prior to 5.5-24, but already more or less does this for 5.5-24 and 6.x.   The main issue is that due to a bug in the fppos upgrade in the versions prior to 5.5-24, nothing in the upgrade process called any scripts in the fppos file.   Thus, we could not inject any checks or fixes or workarounds or anything.    Starting with 5.5-24, the upgrade process properly calls into the scripts within the fppos and those scripts could do things like display an error or fail to run or (preferably) workaround any issues.

**Comment by MrPaulAR** [comment]
Closing as fix exists where it can.
