### ISSUE TITLE
FPP OS 6.1.1 - Random MAC addresses in DHCP request

### ISSUE THREAD

**Issue by Vlad-Star** [FalconChristmas/fpp#1371]
My home network includes DHCP server running on Cisco Catalyst 4948, with configured static DHCP mapping.
I have two Raspberry Pies, FPP-200 (RPi 3B) and FPP-210 (RPi 4), with their eth0 interfaces connected to the switch.

After upgrade to FPP OS 6.1.1 I am seeing random MAC addresses in DHCP requests, which breaks static mapping

### DHCP server configuration on Cisco switch (static MAC-to-IP mapping):
```
C4948#sh ru | inc 64.200
   address 192.168.64.200 client-id 01b8.27eb.e492.c1
C4948#sh ru | inc 64.210
   address 192.168.64.210 client-id 01dc.a632.c9e1.c2
C4948#
```

### FPP OS 5.3
DHCP requests use true MAC addresses from the primary eth0 interface of each RPi, which match the static rules
```
C4948#sh ip dhcp binding | inc 64.200
192.168.64.200  01b8.27eb.e492.c1       Infinite                Manual     Active     Active     ### FPP-200
C4948#sh ip dhcp binding | inc 64.210
192.168.64.210  01dc.a632.c9e1.c2       Infinite                Manual     Active     Active     ### FPP-210
```

### FPP OS 6.1.1
DHCP requests use some random MAC addresses, which don't match static rules, therefore getting different IP addresses from the dynamic pool. Note the 2nd field.
```
C4948#sh ip dhcp binding | inc 65.153
192.168.65.153  ff4b.7ec7.0b00.0200.    Oct 03 2022 06:54 PM    Automatic  Active     Vlan5     ### FPP-200
C4948#clear ip dhcp binding 192.168.65.153
C4948#sh ip dhcp binding | inc 65.154
192.168.65.154  ff75.9dbd.1600.0200.    Oct 03 2022 07:02 PM    Automatic  Active     Vlan5     ### FPP-210
C4948#sh ip dhcp binding | inc 65.156
192.168.65.156  ff0b.daec.5f00.0200.    Oct 03 2022 07:03 PM    Automatic  Active     Vlan5     ### FPP-200 (after reboot)
C4948#
```
I.e. even if I clear the binding, next DHCP request comes from another random MAC address, rather than the one assigned to eth0 interface. I had to roll back to FPP OS v5.3.

**Comment by mjunek** [comment]
I was just looking at this same issue as it mucked up all my reservations

It appears that Debian 11 is now using Systemd-NetworkD, which is creating a random "client-id" and sending it in the DHCP request, rather than the standard client-id of 01:hardware address, or blank, allowing MAC based allocation.

This is from a BBG running FPP 6.1-
![image](https://user-images.githubusercontent.com/55641392/194464924-064c033f-96cb-4a87-bcbb-9e541e04f334.png)

And by comparison, a windows PC- note the ClientID and MAC address are the same, with 01: prepended to the client ID
![image](https://user-images.githubusercontent.com/55641392/194465029-d8aa8af2-495c-4cfa-b1f2-a1e4e705d4a6.png)

And MacOS:
![image](https://user-images.githubusercontent.com/55641392/194465418-e676f25b-dcb3-44d3-903b-c14e49535f0b.png)


I will submit a PR shortly to address the issue which will force the MAC address based client-identifier to be used in DHCP requests as per previous operation; it requires some minor changes to the start-up scripts

**Comment by ptr727** [comment]
No wonder, I updated, an suddenly could not connect using host name, looking at DHCP device got a brand new IP, and DHCP-DNS name was not resolving, had to access device using IP address.
