### ISSUE TITLE
After Hours Plugin - can others verify that this is not working in 6.x?

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#1396]
The plugin page says to install a couple of packages and reboot. That is done but the plugin page doesnt seem to change.

**Comment by jcrossbdn** [comment]
I tested on a fresh 6.1 and it installed properly.Can you try running the commands it says it needs to run on the command line and see if any errors are returned?JasonSent from my iPhoneOn Nov 1, 2022, at 9:57 AM, Daryl ***@***.***> wrote:﻿
The plugin page says to install a couple of packages and reboot. That is done but the plugin page doesnt seem to change.

**Comment by derwin12** [comment]
That's what we ended up doing .. running the commands from the linux .. the plugin page never seems to change. So you cant really use it. It only ever says to run the apt install packages.

**Comment by derwin12** [comment]
Doing the install on 5.5 quickly comes back with the right UI.
![image](https://user-images.githubusercontent.com/4643499/199295158-5132c032-ec63-47bd-ae0c-a7e3bd2eb4e3.png)

**Comment by nmiller0113** [comment]
Working great for me on a fresh install of 6.1.1.

**Comment by derwin12** [comment]
Ok .. I wonder if the zoom roomer was doing something wrong in the url on the browser. I see looking at the code, the url contains the code to show the startupscript. So if he kept hitting that same url, it would always show the startup/install script.

**Comment by jcrossbdn** [comment]
Yes correct.Always best to use the menus in the ui if they aren’t.Now if something does show up as being wrong I’d love to know about it so I can investigate and release an update if required :)Most issues I’ve seen in the past is the apt processes not working properly, usually due to no internet route on that particular pi or a dns config that breaks everything, haha.JasonSent from my iPhoneOn Nov 1, 2022, at 1:28 PM, Daryl ***@***.***> wrote:﻿
Ok .. I wonder if the zoom roomer was doing something wrong in the url on the browser. I see looking at the code, the url contains the code to show the startupscript. So if he kept hitting that same url, it would always show the startup/install script.

**Comment by nmiller0113** [comment]
@jcrossbdn, not to piggyback on this, but since I noticed you were very responsive, I thought I'd mention that I opened two issues today under your plugin (nothing urgent, as everything is working). I just wanted to bring it to your attention :) Thanks!

https://github.com/jcrossbdn/fpp-after-hours/issues/14
https://github.com/jcrossbdn/fpp-after-hours/issues/15

**Comment by jcrossbdn** [comment]
Thanks!Tab background is now fixed and available as an update from the plug-in page.Second item I’m hoping you can run some more tests and share the specific command output responses.  All details in the GitHub issue.Thanks,JasonSent from my iPhoneOn Nov 2, 2022, at 11:20 AM, Nathan MIller ***@***.***> wrote:﻿
@jcrossbdn, not to piggyback on this, but since I noticed you were very responsive, I thought I'd mention that I opened two issues today under your plugin (nothing urgent, as everything is working). I just wanted to bring it to your attention :) Thanks!
jcrossbdn/fpp-after-hours#14
jcrossbdn/fpp-after-hours#15
