### ISSUE TITLE
FPP stops responding to web requests, but responds in incognito window

### ISSUE THREAD

**Issue by ptr727** [FalconChristmas/fpp#1436]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 6.2 on K4-PB

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Browse around the web UI
2. Web UI stops responding
3. Chrome stays in loading state
4. Open Incognito window in Chrome
5. Browse the same site in incognito view that is hanging in normal view
6. Open SSH connection, reboot, site is accessible again
7. Browse around, starts hanging again, incognito works again

**Expected behavior**: 
Site remains responsive.

**Additional context**: 
Chrome developer tools network shows pending.

**Additional Attachments**
N/A

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/2061579/206949918-d993c1db-008e-4df9-aa84-76d5fd1997ab.png">

**Comment by darylc** [comment]
Is it just the multisync page or all pages?

What does fppd.log/syslog/apache logs say?

**Comment by ptr727** [comment]
It happens randomly on various pages.
Location of `fppd.log/syslog/apache` please ?

**Comment by ptr727** [comment]
I don't know how to get just apache logs from SSH, but here are zipped logs from file manager created from the incognito window while the normal chrome window was unresponsive.
[FPP_Logs_20221216.0423.zip](https://github.com/FalconChristmas/fpp/files/10242667/FPP_Logs_20221216.0423.zip)

**Comment by jaredb7** [comment]
I run into this a few times when I was developing the automatic settings backup thing. It wouldn't happen all the time and once it had wouldn't happen again for a while.

Sometimes would happen changing a setting, calling the API or viewing the status page. I think it's a re-occurrence of a issue we had a few years ago when 2 php scripts would get into a deadlock like condition accessing the PHP Session state. 
There's generally nothing in the logs for this as both scripts are still technically executing but just stuck,

The reason why it works in a incognito window is because a new PHP session when serving those requests and we're not working with the locked one in the other window..

I haven't investigated much further but may have a poke around.
