### ISSUE TITLE
BRANCH playlist item delayed by one slot

### ISSUE THREAD

**Issue by bluecreeklightguy** [FalconChristmas/fpp#1438]
FPP 6.1.1, running on RasPi4.

When I use the BRANCH playlist item in a playlist, and the conditions are met, the scheduler first plays the next playlist item and then comes back and plays the BRANCH item.

For example, with the attached screenshot, I have a BRANCH item as entry #2.  When the conditions of the branch are met (I'm using the time to determine whether to insert a bumper into the current running playlist), the scheduler plays entry #3 and then plays the BRANCH at entry #2, then continues with entry #4 and wraps back around.  It continues to work this way every time through the schedule.

Expected behavior:  when BRANCH condition is met, it would play immediately, instead of playing the following entry and then returning to play the BRANCH.

<img width="883" alt="Screen Shot 2022-12-13 at 12 46 00 PM" src="https://user-images.githubusercontent.com/71750486/207419427-9f30adf7-26c3-4afb-aabc-4d7520c911e3.png">
<img width="1421" alt="Screen Shot 2022-12-13 at 12 46 53 PM" src="https://user-images.githubusercontent.com/71750486/207419432-d698a3ec-658c-4d80-8438-a3a68f7bc85d.png">
<img width="1415" alt="Screen Shot 2022-12-13 at 12 47 17 PM" src="https://user-images.githubusercontent.com/71750486/207419437-086be644-54e3-4b73-88ff-bd89037043a4.png">

**Comment by darylc** [comment]
I have replicated this in the latest master

**Comment by darylc** [comment]
This problem is caused by [src/playlist/Playlist.cpp](https://github.com/FalconChristmas/fpp/blob/master/src/playlist/Playlist.cpp) line 816:
            m_sectionPosition++;

If I remove that, the branch occurs in the correct spot, however on return it is stuck testing the branch again and I can't find an elegant way to advance the position of the original playlist before it resumes from its pause after the branched playlist is finished.
