### ISSUE TITLE
Channel Outputs cleanup for v1.5

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#145]
RPIWS281x (remove unless confirmed working)
SPI-WS2801 (remove SPI device selection unless confirmed working)
Generic
- Include tty0* in serial port list for BBB onboard
- Fix tty0* and ttyAMA* so they can't be used for DMX on Pi
- disable console output to ttyAMA0??

**Comment by ihbar** [comment]
Hello
Why do you want to "Fix tty0* and ttyAMA* so they can't be used for DMX on Pi"  ?
USB DMX on tty0 is working fine.

**Comment by bigwavedave42** [comment]
Yes, the tty0* is for hardware serial ports on the BBB and the ttyAMA* is for the hardware serial ports on the Raspberry Pi.  Some people would like to make use of the hardware serial ports, instead of using USB.  They don't have any plans to remove the USB tty, so don't worry about losing any functionality!  This is just providing more options for people to create things.

**Comment by cpinkham** [comment]
ttyS0 is USB serial.  ttyO* is onboard serial on the BBB.  ttyS* works fine for DMX, but ttyO* don't on the BBB.  I want to make sure that when we do add ttyO* support on the BBB for Renard, LOR, etc., that it doesn't show up for DMX/Pixelnet use.  I think that is handled already but wanted to make sure it wasn't missed.

**Comment by ihbar** [comment]
ok, thank you for the clarification.

**Comment by cpinkham** [comment]
These changes were pushed already, closing ticket.
