### ISSUE TITLE
Backup during "Initial Setup"

### ISSUE THREAD

**Issue by Noelle88** [FalconChristmas/fpp#1586]
Last year I had 6.0 installed (RPI3b+). I had no problem there.

Now Halloween 2023 is coming up and the show is being expanded.
That's why I expanded to FPP 7.1 (RPI4b 4GB + RPI3b+ + RPI Zero 2 W).

Now I have the problem (regardless of which PI) that when I make settings and reboot, the respective PI can no longer be reached via WiFi. Neither via WiFi nor via SSH.
I get the “Initial Setup Mask” displayed via LAN. But when I press "Finish Setup" it starts again from the beginning.

I've had this phenomenon with the “Initial Setup Mask” a few times with newly created images.
I flashed my images using BalenaEtcher or Raspberry Pi Imager.

Unfortunately I cannot reproduce the error myself.

But I wish you could skip the “Initial Setup” or integrate the “Load from Backup” function.

**Comment by Poporacer** [comment]
Due to recent IOT laws, the initial Setup Setup page is required. Without more info on what settings you are changing, we really can't help you. I personally have upgraded 10 FPP devices to 7.0 and then 7.1 (all on Wi-Fi except one) and also have helped a few dozen others do the same thing and have not seen that problem. I have a feeling that there is something you are doing in the initial setup page?

**Comment by ghormann** [comment]
Closing as need Info for multiple months.
