### ISSUE TITLE
Performing upgrade on 7.2 (to apply the latest commit) shows errors about resolving hostname

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#1599]
![image](https://github.com/FalconChristmas/fpp/assets/4643499/2f22c60e-78a3-4b3f-bbcc-83d2f577684f)

Various messages in the log about unable to resolve the host name. Yes the host is BlackTopPiCap
Note that blackTopPiCap.local does not work from the url.
Upgrade was done from the http://192.168.0.174/about.php page .. ie the IP address.
It appears the upgrade did complete. Not sure why it was so messy considering it was just one commit in the preview of the changes.

**Comment by harriscd** [comment]
I have noticed these errors in the upgrade window going to 7.4.3, as well as in a SSH session (e.g., running command `sudo systemctl`).  I feel like this may have been caused a while ago when I was trying to set up my Pi as a bridge between the home network 192.168.1.0 and a dedicated show wifi router on 192.168.2.0

There were a few websites that mention this error caused when there is a discrepancy between /etc/hostname & /etc/hosts  ... in my case in the /etc/hosts file there was an old hostname entry `127.0.1.1   FPP`.  I'm currently using host name of FPP-Pi4, so that was wrong in my case. 

<img width="388" alt="image" src="https://github.com/FalconChristmas/fpp/assets/69568320/ab6adaff-7eb9-49dd-9a3c-e1e4b558d3a6">

To fix my controller, I added a **new** line for `127.0.0.1   FPP-Pi4`  and changed the **existing** 127.0.1.1 line to be `127.0.1.1   FPP-Pi4`   So far looks like that has stopped the error in SSH.

I followed the guide here:  https://linuxhandbook.com/sudo-unable-resolve-host/

**Comment by darylc** [comment]
The only way this can happen is if /etc/hosts didn't get updated.  There have been lots of changes since this issue was created, I've done a bunch of testing in FPP 8 and cannot get this to occur.  Closing this issue for now, we can re-open it if we find an instance of it occurring in FPP 8 in the future.
