### ISSUE TITLE
Images in Playlist seem to not work

### ISSUE THREAD

**Issue by GitHubGoody** [FalconChristmas/fpp#1636]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
*FPP 7.3.1 running on RPi Zero W*

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Create a Playlist with an image (1920 x 1080 .png) and a pause immediately after it as instructed in the Falcon Player manual (pg. 105...excerpt below*)
2. Try to play the playlist
3. Observe that the image does not display. Instead, the boot IP screen remains displayed until the pause duration elapses and the playlist starts with the file following the pause (e.g. the .mp4 in my screenshot below).

**Expected behavior**:
The .png should display for 10 seconds followed by the .mp4.

**Additional context**: 
The .mp4 runs fine indicating the playlist and video are both good.

**Additional Attachments**
[FPP_Logs_20231107.0226.zip](https://github.com/FalconChristmas/fpp/files/13274867/FPP_Logs_20231107.0226.zip)

![image](https://github.com/FalconChristmas/fpp/assets/46235745/c0e94075-0c9f-4833-b6f0-b4a6be19734f)

```
* Image- You can display images through the HDMI port. This could be useful if you 
want to have a virtual “picture frame” You can select all of the images that are in your 
Images folder by entering /home/fpp/media/images for the path. Or you can select 
individual images by entering the image file name. You will select the transition type 
that you want in between images. Then you would add a Pause Entry for the amount 
of time that you want the image to display. If you are displaying individual images, you 
will need to add a Pause entry after each picture for how long you want the image to 
display before it transitions to the next one. If you select the Images path, FPP will 
play the images in a random order
```

**Comment by cpinkham** [comment]
2023-11-06 18:49:26.324 (1537) [Playlist] /opt/fpp/src/playlist/PlaylistEntryImage.cpp:88: Invalid Pixel Overlay Model: 'null'

You have to create a pixel overlay model for the fb0 framebuffer output and select that model in the playlist entry.  The image is displayed to a model, so you can display to the video output or even to a pixel matrix.

**Comment by GitHubGoody** [comment]
@cpinkham Ok, thanks. How do I display to the HDMI out on my RPi Zero W?

**Comment by derwin12** [comment]
Neat feature ... so I would assume you need to create a matrix item in your layout. Put it on your Pi so it knows the start channel/ Then upload your outputs, tools fpp-connect to push the models. Now when you create the playlist, select the matrix in the new sequence entry (mine is a tv)
![image](https://github.com/FalconChristmas/fpp/assets/4643499/d648a1af-e521-4325-b489-4345accbac9f)

**Comment by cpinkham** [comment]
You need to go to the Pixel Overlay Models page which is under the "Input/Output Setup" menu.

On that page, use the Add button to create a model of the 'framebuffer' type and set the resolution in the size fields and the virtual pixel size.   If you want high resolution pictures, you can use a pixel size of 1.  If you are simulating a virtual matrix, use the same pixel size so you can see the virtual pixels.  Save the model.

On the playlist page, edit the image entry in the playlist and select your new Pixel Overlay Model from the dropdown list.  Save the playlist and then go play it.

I use FPP to drive several digital picture frames using old Pi 2 B's and 16:9 DVI monitors, so the basic image display functionality is one of the most tested functions in FPP since it runs on picture frames in my house about 14 hours a day every single day.

**Comment by cpinkham** [comment]
> Neat feature ... so I would assume you need to create a matrix item in your layout. Put it on your Pi so it knows the start channel/ Then upload your outputs, tools fpp-connect to push the models. Now when you create the playlist, select the matrix in the new sequence entry (mine is a tv) ![image](https://user-images.githubusercontent.com/4643499/281063947-d648a1af-e521-4325-b489-4345accbac9f.png)

This isn't an xLights model, it's an FPP feature.  In this particular case, it doesn't even use channels since it displays the image right to the framebuffer.  You can use it with a FPP Virtual Matrix though, and then you'd need to do some things like you describe so you can sequence onto the HDMI output.

**Comment by GitHubGoody** [comment]
@cpinkham Thank you. I appreciate your help in what was initially meant to be an issue (clearly due to my noob'ness). If we can just close the loop on how I've implemented your suggestions, I'll close the issue...

> You need to go to the Pixel Overlay Models page which is under the "Input/Output Setup" menu.
> 
OK, I've pieced together many YouTube videos and your replies (I think properly ;-)) to get to this point:
![image](https://github.com/FalconChristmas/fpp/assets/46235745/7db01d25-7d08-4484-ba38-2dc006f89c20)

My understanding of this configuration is...

The first row is the VM I created in xLights (then uploaded via FPP Connect) to be used in the event I ever want to reduce the resolution of my projector so it emulates a low resolution pixel display for displaying xLights effects with manageable sequence sizes. The is meant to be used in xLights/sequences.

The second row is the frame buffer (now at least I know what fb0 stands for) configuration you recommended for directly outputting images or video to the HDMI port on my projector at its native resolution (i.e. I don't think setting 1920x1080 here is a big deal since it's _not_ mapped to channels like in xLights/sequences). This is _not_ meant to be used in xLights/sequences.

**Right so far?**

> On that page, use the Add button to create a model of the 'framebuffer' type and set the resolution in the size fields and the virtual pixel size. If you want high resolution pictures, you can use a pixel size of 1. If you are simulating a virtual matrix, use the same pixel size so you can see the virtual pixels.
> 
Why would I want to simulate a virtual matrix if it cannot interact with xLights (where effects are programmed)? Wouldn't I want to use the VM I configured in the first row above for that use case?

> On the playlist page, edit the image entry in the playlist and select your new Pixel Overlay Model from the dropdown list. Save the playlist and then go play it.
> 
Done. I'll test it tonight.
![image](https://github.com/FalconChristmas/fpp/assets/46235745/c7e8623d-9bb3-4fab-8871-4f75bf77eca0)

> I use FPP to drive several digital picture frames using old Pi 2 B's and 16:9 DVI monitors, so the basic image display functionality is one of the most tested functions in FPP since it runs on picture frames in my house about 14 hours a day every single day.
Cool use case!

**Comment by cpinkham** [comment]
What was the playlist playing when you tried to stop it?  The pause or the mp4?  My old 16:9 monitors are 1600x900 and 1376x768 but there shouldn't be any issue with 1920x1080.  Was there anything in the fppd.log file from before the reboot?

**Comment by GitHubGoody** [comment]
I had to take a step back and sort out the [freezing issues](https://github.com/FalconChristmas/fpp/issues/1640). My issues centered around trying to drive 1920x1080 videos on an RPi with the GPU memory capped at 128MB.

Now that I think I have a stable setup, I can get back to this.

Would you mind reading the first half of my previous post and confirming/correcting my understanding of the two projector configurations (VM vs POM)?

Additionally, what I don't understand is why FPP allows for direct output to default (i.e. HDMI out) for videos, but not for images. With a Playlist entry set to `Media Only | Single File`, default is available under `Video Out` (screenshot 1), but images are not available in the `Media` dropdown. Instead, I have to change to `Image` which allows me to choose an `Image` file, but requires the selection of a `Pixel Overlay Model` instead of simply choosing a `Video Out` (screenshot 2). If anything, it seems this would be the other way around since images are a single frame (less processing required) compared to ~30 fps video.

**Screenshot 1**
![image](https://github.com/FalconChristmas/fpp/assets/46235745/30b66918-0792-49e9-b0f8-49a004c99339)

**Screenshot 2**
![image](https://github.com/FalconChristmas/fpp/assets/46235745/c83cc773-1b4c-4bb1-b9ed-a77d2f9d5b84)

**Comment by cpinkham** [comment]
There are multiple things in play here.  

The "Garage Projector" model you have is just a model which allows you to use the model in FPP for plugins, image output, etc..  Data put on the model is written to the channels defined in the model config.

The "Garage Projector Pixel Overlay" model is not channel based, but instead writes to the framebuffer and video output.

The Virtual Matrix channel output code actually uses a Pixel Overlay Model behind the scenes even when you tell it to write to the framebuffer, it creates a framebuffer POM on the fly and uses that to write to the video output.  It works this way so we aren't duplicating framebuffer writing code in multiple places.

The video playback code uses the VLC library for decoding and playing video  using hardware acceleration.  It can optionally write to a POM.  The image playback code writes to a POM, again so that we minimize duplication of code to do things like write to the framebuffer.  We could probably add code to have the image playlist entry code auto-create a framebuffer POM, but haven't spent time to do that yet.

POMs can also write to regions of other POMs as well.

When I said "simulate a virtual matrix", I was just referring to the low resolution of a matrix vs a full video output.

**Comment by GitHubGoody** [comment]
Awesome explanation! Thank you. I might need to read it a few more times to understand it enough to apply properly! 🤪

For video, maybe the thing I need to understand most immediately (based on my other issue) is which of these three output methods yields the best resolution with the lowest GPU demand.

**Comment by cpinkham** [comment]
If you are playing a video, you should play straight to HDMI unless there is a reason not to.  The other options are there to allow you to play a video to a matrix or other non-HDMI solution.
