### ISSUE TITLE
Display Testing of an FSEQ file when in Remote mode

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#166]
After a fresh boot of my BBB / Octoscroller, I can't play an FSEQ file under Display Testing.

No output.

But, if I go to the Master and play a sequence that involves the P10, from then on the Display Testing works immediately.

I will see if it is just the P10 or just BBBs. It has been very repeatable.

**Comment by JonB256** [comment]
Did it on a BBG / F4B in Remote mode also.  Not just on reboot, either. If I "Restart" FPPD, it won't play a FSEQ until it is first sent data from the Master.

**Comment by cpinkham** [comment]
I know why this is happening but need to think of a way around it.  When the channel output thread starts on a remote, it waits for the master to start sending sync frames so that the remote can start in sync.  That was breaking effects, channel testing, and Pixel Overlay on Remotes because the channel output thread would stop if it didn't get any update from the master.  I have fixed that in master, but the fix didn't include changes to allow sequence testing on a Remote because that was a little harder to fix.  I made a note and will get this fixed, it should be in v1.6.  I have a couple ideas, I just need to pick a solution and implement it.

**Comment by cpinkham** [comment]
This won't make it in this year.  For now, the solution is to test the sequence on the master which will also fire the sequence on the remote.

**Comment by cpinkham** [comment]
Is this still an issue in FPP v3.5.x?  I haven't heard this kind of thing mentioned in a long time.

**Comment by cpinkham** [comment]
Closing this since in FPP v4.0 Alpha as of 019b3eba27 you can now play a sequence file directly from the FPP Status and File Manager screens.  You do not need to create a playlist for the sequence, FPP creates a playlist on the fly in memory and automatically selects the accompanying media file to go with the sequence based on the metadata stored in the .fseq file.
