### ISSUE TITLE
Auto-Scroll Checkbox

### ISSUE THREAD

**Issue by McCoyCOREUSA** [FalconChristmas/fpp#1701]
This isn't a bug, but just reporting on this new checkbox to auto-scroll to active playlist on the Status page.

When there is a longer list, this prevents the user from scrolling up to the top of the entire screen. It immediately keep jumping back down to the active item when it's down the list a way. Not sure of a fix for this? Just reporting as feedback.

**Comment by Poporacer** [comment]
The purpose of the Auto Scroll is to keep the currently playing item visible in the window. That is so that if you have a long playlist and you just want to monitor how the show is progressing, you don't have to keep scrolling to see what is actively playing and FPP will Auto Scroll to that item. It is working as designed, you told it to keep the currently playing item centered in the window and then you manually tried to scroll to the top, but FPP did what you told it to and re-centered the playing item....The fis is to uncheck the Auto Scroll, LOL
