### ISSUE TITLE
Popup to warn if playlist not saved

### ISSUE THREAD

**Issue by blargh2947** [FalconChristmas/fpp#1724]
**Is your feature request related to a problem? Please describe.**
As a user, I'm frustrated that I make changes/updates to a playlist and then forget to hit "save playlist" before exiting the page and my edits are all lost.

**Describe the solution you'd like**
Add a configuration setting to automatically save the playlist after an entry is updated.

At the least, a nag when you try to navigate off the page of "unsaved changes" would be helpful.

**Describe alternatives you've considered**
N/A

**Additional context**
This would save time and frustration when working with playlists.

**Comment by jazakrzewski** [comment]
A reminder of unsaved changes would be great!

**Comment by OnlineDynamic** [comment]
I've fallen into this trap so would second some kind of mechnism to prevent losing changes by mistake

**Comment by cpinkham** [comment]
I think this would be better implemented as a popup to warn you if you try to leave the page or exit the playlist without saving changes.  Auto-saving could have the same bad impacts if users make a change they decide not to save, then wipe out a good playlist with a bad playlist because they had the setting turned on.
