### ISSUE TITLE
Audio ducking (Announcments)

### ISSUE THREAD

**Issue by focusedonsound** [FalconChristmas/fpp#1728]
While playing a show to have the ability to play a secondary announcement which causes the existing audio to go down a bit in volume, and the secondary audio to play.

Viewers watching the show often disregard show messaging, and turn around in neighbors driveways, turn their radios up louder than necessary, etc.  It would be optimal to have a set of pre-canned audio messages which from a button in FPP you could play an audio message telling the viewers to 'Turn down the volume' , or 'Please be courteous and dim your headlights' 

Alternative solution would be to implement a secondary fpp  that holds the audio file, when playing the audio on this device.  It would send a command to turn down the volume on the primary fpp, and then play the necessary audio file from the secondary fpp at the end of the file it would send a command to turn the volume back to its original state.

None at this time

**Comment by Poporacer** [comment]
I don't know if the program that FPP uses can support 2 audio sources or not. We will see if we get a response from someone that knows better. But I do somethings similar, I have a couple sequences created for "Turn your Radios down, "Don't block driveways", etc. and then I use an FPP Command to Insert Playlist Immediate with the appropriate sequence. I think it might be more effective that instead of the audio ducking and just an audio announcement that the current sequence is actually paused and some flashing red an blue lights start and the appropriate announcement plays?

**Comment by focusedonsound** [comment]
The preference would be to NOT stop/pause the currently playing sequence, but understand there are limitations.  I know several people have mentioned to me that this would be quite helpful to them and I know that I have several use cases for this type of feature.

**Comment by darylc** [comment]
We would welcome a pull request for this functionality, but it seems unlikely this will get done without it.
