### ISSUE TITLE
Ability to copy an item on the playlist edit screen

### ISSUE THREAD

**Issue by OnlineDynamic** [FalconChristmas/fpp#1729]
I'm using a playlist to create a set of remote run script commands I would like to execute.

There is lots of reputition in what needs to go into the playlist entries with minor config edits to the args submitted to the remote scripts on each entry.

It would be helpful if we were able to "Clone" (duplicate) a line in the playlist in the same way you can duplicate a line in the scheduler UI

**Comment by cpinkham** [comment]
This is already in FPP v7.4.  Click the edit button to edit a playlist entry, change what you want, and select 'Save As New' instead of 'Save' and it will create a new entry below the one you clicked Edit on.  Then you can move that item anywhere in the playlist.  If you edit and then Save As New without changing anything, it will duplicate the item.
