### ISSUE TITLE
Add a "reboot on no network" option

### ISSUE THREAD

**Issue by cjalmond** [FalconChristmas/fpp#1736]
**Is your feature request related to a problem? Please describe.**
During the season I had multiple Kulp controllers boot to "no network".  100% of the time a reboot brought them back online.  I am of the opinion that if an option was available in the UI to "force reboot on no network" I would check this option to allow the controller to reboot on its own if no network is found.  The justification is the controller is down 100% so rebooting until a network is available is a good choice.   The only stick part is there will have to be an option on the controller via the menu to disable this option if you wish together out of a forever reboot mode.

**Describe the solution you'd like**

**Describe alternatives you've considered**
I am not sure of other options but I am sure there is some but this is my sipper option to resolve my controller down issues due to no network.  BTW, this happens on Blacks more often than pocket beagles.

**Additional context**

**Comment by Poporacer** [comment]
What version of FPP are you running and are you powering down your controllers/router/switches and then powering them back up and that is where you run into problems? Please describe your operation in more details.
Having the "auto reboot" could be problematic. Every network will take a different amount of time to negotiate a connection so this "auto reboot" would need to wait long enough to connect and like you mentioned, this reboot could cause an endless loop...
This would also probably defeat the Tethering mode that is designed partly to get into systems that fail to get a valid network connection.

**Comment by cjalmond** [comment]
This happened last season on 6.3 and this season on 7.1, 7.3, and 7.4.  There is probably a much more elegant way to deal with this after I have thought about it more.   I honestly never tried a reboot because the controllers are buried in boxes and it is hard to get to the menu buttons so I always powered down.

**Comment by Sven-v-Beuningen** [comment]
Just in case you didn't notice: I have the feeling, that this issue is related to this very long discussion about network issues on the BeagleBone boards:
https://forum.beagleboard.org/t/beaglebone-black-ethernet-phy-not-detected-on-boot/95
https://wp.josh.com/2018/06/04/a-software-only-solution-to-the-vexing-beagle-bone-black-phy-issue/

I also have the issue, that the network won't come up after boot. I think it is about 50% of the time. Only solution so far is to power cycle. Unfortunately this won't be possible in the future for me, because I can't reach the board easily in my installation.
It would  be awesome if one of the discussed fixes could be integrated into the FPP image to solve, or at least deal with this issue.
Therefore I also vote for a auto-power-cycle option if the network won't come up.

**Comment by darylc** [comment]
Network issues should be fixed properly rather than with reboots.
