### ISSUE TITLE
Wrong Playlist Playing

### ISSUE THREAD

**Issue by Jchuchla** [FalconChristmas/fpp#1746]
**FPP Version and Hardware**: 
[v7.x-master-417-gddec08e9 (master branch)] on Pi 3b+

**Describe the bug and Steps to reproduce**: 
My Christmas show is scheduled to run from Black Friday thru Epiphany.  I use the named holidays in the schedule.  There are several schedule entries related to the christmas show.  While it may look like a lot, These are intentionally nested and ordered to create a prioritized schedule order to handle pre and post show lights, as well as extended show hours for Christmas eve, Christmas day and New Years Eve.
After Epiphany, I have a single scheduler entry scheduled from Jan 7 thru Jan 31.  This runs a "Winter Blue" playlist from 4pm thru 7:30am every day for the rest of January.

**Expected behavior**: 
Today is Jan 7, at 01:43 am.  I expected the winter blue playlist to be running.  But instead it's playing the Overnight Lights playlist. 
Even after rebooting the pi, it is still playing the Overnight Lights playlist.  It shows the next playlist as winter blue to start at 4pm on Jan 7th.

**Additional context**: 
Schedule file attached:
[schedule.json](https://github.com/FalconChristmas/fpp/files/13852583/schedule.json)

**Comment by Poporacer** [comment]
If I understand it correctly, your Overnight Lights playlist was scheduled to run through Epiphany (1/6) so it started on 1/6 at 22:00 hours and was scheduled to end the next morning at 07:30 so it was playing within the scheduled time frame when you looked at 01:43 on 1/7
Your Winter Blue was scheduled to start on 1/7 from 16:00 to 07:30. Since it is 01:43 on 1/7 your Winter Blue should not be playing since it hasn't been "triggered" by your start time which is 1/7 at 16:00 hours.

**Comment by Jchuchla** [comment]
There's two things here that are suspect.
First, if I restart FPP after midnight on 1/7, I wouldn't expect "overnight lights" to start.  It shouldn't ever start on 1/7 if it's schedule was set to end on 1/6.  I could understand that if it started on 1/6 and crosses over midnight to the next day, that it would play out till the end of its scheduled time outside of the date window.  But on an FPP restart after midnight, I wouldn't think it would start if the date doesn't match anymore.
Second, I would have expected FPP to conclude that the current time is within the window of 4p-7a and since it's 1/7, it should start the schedule that matches for both the time 4p-7a and the date of 1/7.
It seems like it's only checking the time and date at the start of the scheduled window, not for the whole duration of the window.

**Comment by Jchuchla** [comment]
I should note that this isn't a major issue.  It's not that big of a deal that after midnight on the 7th of January my lights were dim red and green instead of blue and white for just the one night.  But I wanted to explore whether this is actually by design or is a flaw in the scheduling logic.  And I want to better understand the expected behavior.  It would matter more on a night like Christmas Eve or New Years Eve.

**Comment by Poporacer** [comment]
On your first point,
I see your point that even though "today" is 1/7 that the Overnight lights shouldn't start, yes it is scheduled to end on 1/6 but your schedule for the Overnight lights IS scheduled to end on 1/6 (this is the last day it is scheduled to play) but it is still actually scheduled to end on 1/7 at 07:30 hours (this is still part of your 1/6 Overnight Lights schedule) I think FPP looks at the entire schedule and even though it is after midnight, it is still within your defined schedule so it will still be playing. 
On your second point, 
Your start schedule for your Winter Blue isn't until 16:00 on 1/7, so the Winter Blue schedule doesn't become "active" until 16:00 hours... It is NOT within your scheduled window for Winter Blue to play at midnight on 1/7. FPP honors your actual scheduled Start time...That would be problematic if FPP were to start schedules before the actual start Date/Time.
You stated that you thought FPP should be running the schedule that matches both the time and date of 1/7? It does, but only during the time periods that you have defined for the schedule to be active and since you told FPP to start this schedule at 16:00 hours on 1/7, then at midnight of 1/7 your Winter Blue schedule is not matching the time and date that you set for your schedule.
Based on your schedule and your reported observations, it does look like FPP is checking your entire schedule to play according to your schedule.
To me it looks like it is working properly and per your schedule. 
Maybe this will help?
FPP looks at the Start and end Dates and times to determine when a schedule should be "active". 
The Start time is a little more straight forward. In your case, your Winter Blue schedule does not become active until after 16:00 on 1/7.
The ending of the Schedule is determined by the end date (the last day that this schedule will **start**) and the scheduled end time. So your Overnight Lights schedule was in an "active" State from Black Friday at 22:00 hours until 1/7 at 07:30 hours.

**Comment by cpinkham** [comment]
Confirming what Rick posted.  Based on the scenario described, FPP is working as designed.

FPP only looks at the start times when laying out the schedule, so if a time slot starts within the date range, it will get played.  The schedule entry starts/ends on the dates specified, but that doesn't mean the playing item can't go past midnight on the end date.  The player won't stop after 23:59:59 on the end date because it is suddenly out of the date range.  Similarly, it won't start playing something at 00:00:00 on the start date because it entered the date range for a scheduled item which was scheduled from 4P-7:30A.  The scheduler doesn't really look at the date of the end time on the time slot, it just understands that if the end time is less than the start time, it needs to add 24 hours to the stop time to push it into the next day.

**Comment by Jchuchla** [comment]
I can live with this so long as I know that's what's expected.
@cpinkham can you confirm the situation of the FPP restart after midnight.  Is it expected that it's supposed to look back to the previous day to see if something should have started yesterday and still be running.

**Comment by Poporacer** [comment]
This is working as designed.
