### ISSUE TITLE
Can you delay data?

### ISSUE THREAD

**Issue by cathelest** [FalconChristmas/fpp#1747]
Currently have a pi4 running as master, with a pixel hat running 2 output for garage outlines

It then outputs to my f16v3 and a pi for a projector

With the garage outline which is "local" to the master 

Is there a way to delay the data locally for those ports? As the garage outline will change a fraction wuicker then the rest,

I guess my only alternative would be to grab a second pi and set the pi cap to a slave, but thought i would ask,

**Comment by cpinkham** [comment]
You can't delay the data on the main player, but you can tell the Remote(s) to display quicker.

On your FPP Remote, go to the Settings page and adjust the "Remote Media/Sequence Offset" setting.  This setting allows adjusting the Remote to be slightly ahead or behind the main FPP player.  It doesn't handle making the Remote display the first frame(s) faster because the Remote doesn't know to start, but the remote should quickly adjust its sync to "catch up" to the garage outline.

I don't know how many users are using this feature, I haven't tested it myself in years.  It was added for exactly this scenario where the pixels driven by the main player were not turning on/off at the same time as the pixels driven by a remote.
