### ISSUE TITLE
Notify/Confirm before performing an FPP upgrade that requires an OS upgrade or switches major version.

### ISSUE THREAD

**Issue by Jchuchla** [FalconChristmas/fpp#1785]
This has bitten me more than once now.  Usually before or after the main show season.  I'll be on the master branch because I'm testing some late season fix or something like that, and then when I go to update FPP, it will jump major versions without me realizing the implications.  This time I was on the 7.x master.  I upgraded, expecting it to go to the latest in the 7.x series.  But after the update, I saw that it's now on the 8.x master.  I hadn't upgraded FPPOS, because I didn't know I needed to.  I ran into an issue, and ticketed it, only to be told after the fact that I should have updated FPPOS and the current version is alpha and likely buggy.

Yes I realize I'm running the dev track.  But I'd suspect that there's plenty of people in a similar position to me.  Who switched to this branch for a bugfix, or some specific reason, but is not in close contact with the overall dev team and what's happening overall.  Now I have to make the choice whether to upgrade to a potentially unstable 8.x FPPOS, or revert to 7.5?  I don't even know that 7.5 contains everything in master prior to the 8.x changes. (or even how to find out)

I would not have expected the upgrade button to make my version jump from FPP 7.x master to 8.x master.  Especially without notice.  This kind of jump seems like it needs a warning or notice.  And this should also contain a notice that it requires a newer FPPOS if that's the case.

**Comment by darylc** [comment]
Ultimately these are risks that you take by enabling developer mode in the UI and changing to master branch.    In this case you could revert to 7.5 by changing the Git Branch to v7.5 in the developer tab.  All changes made after v7.5 release are part of 8 and only available in master.

**Comment by darylc** [comment]
To see what changed in master since v7.5, you can go to https://github.com/FalconChristmas/fpp/commits/master and look for all changes after the v7.5 release date

**Comment by Jchuchla** [comment]
That's seriously the response?  Not even offer a check against the OS version, or a warning that the current branch has completly changed direction?

How do you propose that people like me are sure to stay in the loop?

**Comment by Jchuchla** [comment]
The thing is, there WAS a 7.x master.  Then it got renamed to 8.x master.  If master isn't tied to a version, why change the name?  why not just call it master?

Why should I expect this behavior?  All the other discrete versions have their own branch.  Why would the master not get a new branch when it makes a big shift like this?  How would I have known there wasn't going to be a 7.6 or 7.7 before a major change started?

Many of us use the master branch because you guys ask us to.  To test a feature or a fix that covers one of the tickets.  We're not doing it just to be on the bleeding edge.  The "it's the risk we take" argument doesn't really hold any weight.    

This feature request simply closes the loop.  "ok, you might want to stop using master for now.  Version x.x is the last update before major version upgrade"

**Comment by cpinkham** [comment]
You can go to the FPP about page and view the change log screen and click a link and revert to any version you want in the master branch.  You can revert to the commit right before we tagged v8 and started working on v8 items.ChrisOn Feb 1, 2024, at 7:12 PM, Jchuchla ***@***.***> wrote:﻿
The thing is, there WAS a 7.x master.  Then it got renamed to 8.x master.  If master isn't tied to a version, why change the name?  why not just call it master?
Why should I expect this behavior?  All the other discrete versions have their own branch.  Why would the master not get a new branch when it makes a big shift like this?  How would I have known there wasn't going to be a 7.6 or 7.7 before a major change started?
Many of us use the master branch because you guys ask us to.  To test a feature or a fix that covers one of the tickets.  We're not doing it just to be on the bleeding edge.  The "it's the risk we take" argument doesn't really hold any weight.
This feature request simply closes the loop.  "ok, you might want to stop using master for now.  Version x.x is the last update before major version upgrade"

**Comment by cpinkham** [comment]
One more note.  We have a ToDo item for v8 to add something to try to make sure that people are running compatible versions of FPP and the OS.  Depending on how this is implemented, it could include something that could help prevent incompatible upgrades as mentioned.  That being said, we shouldn’t be pushing anything right now that breaks master with the old OS because there is no new v8 image for the beaglebone or docker yet and we don’t want to break those use cases.ChrisOn Feb 1, 2024, at 8:47 PM, Chris Pinkham ***@***.***> wrote:﻿You can go to the FPP about page and view the change log screen and click a link and revert to any version you want in the master branch.  You can revert to the commit right before we tagged v8 and started working on v8 items.ChrisOn Feb 1, 2024, at 7:12 PM, Jchuchla ***@***.***> wrote:﻿
The thing is, there WAS a 7.x master.  Then it got renamed to 8.x master.  If master isn't tied to a version, why change the name?  why not just call it master?
Why should I expect this behavior?  All the other discrete versions have their own branch.  Why would the master not get a new branch when it makes a big shift like this?  How would I have known there wasn't going to be a 7.6 or 7.7 before a major change started?
Many of us use the master branch because you guys ask us to.  To test a feature or a fix that covers one of the tickets.  We're not doing it just to be on the bleeding edge.  The "it's the risk we take" argument doesn't really hold any weight.
This feature request simply closes the loop.  "ok, you might want to stop using master for now.  Version x.x is the last update before major version upgrade"

**Comment by Jchuchla** [comment]
@cpinkham So does that mean my ticket #1784 is a valid bug that should still work properly.  Should that ticket be reopened?

https://github.com/FalconChristmas/fpp/issues/1784

**Comment by cpinkham** [comment]
I reopened #1784 as I think that may be a bug and referenced this ticket in the v8 ToDo item I mentioned #1792 to see what we can do about preventing the situation to begin with.
