### ISSUE TITLE
Caught Signal 15

### ISSUE THREAD

**Issue by thekameleon** [FalconChristmas/fpp#1850]
*NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: v8.x-master-278-g0c331210 (master branch) on Raspberry Pi 4
Sequence created with Xlights 2024.10 on Windows

**Describe the bug and Steps to reproduce**: 
Running a scheduled playlist with one sequence only in FPP

**Expected behavior**: 
To run the full 5 minutes of the sequence

**Additional context**: 
FPPD keeps restarting about every 90 seconds. Log files shows Caught Signal 15 in fppd.log. I also see the red FPPD banner for a split second on the staus page

**Additional Attachments**
Log files attached

[FPP_Logs_20240525.0238.zip](https://github.com/FalconChristmas/fpp/files/15441279/FPP_Logs_20240525.0238.zip)

**Comment by darylc** [comment]
@thekameleon Can you try removing the plugins - eg fpp-nfl and see if it still crashes?

**Comment by brianbarrell** [comment]
Yes.  I have removed all plug-ins. Still have same issue.  Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: darylc ***@***.***> Date: 6/12/24  8:48 AM  (GMT-06:00) To: FalconChristmas/fpp ***@***.***> Cc: brianbarrell ***@***.***>, Manual ***@***.***> Subject: Re: [FalconChristmas/fpp] Caught Signal 15 (Issue #1850) 
@thekameleon Can you try removing the plugins - eg fpp-nfl and see if it still crashes?

**Comment by darylc** [comment]
I'd suggest doing a system reset then, as there is nothing in the logs to give any information about the cause of the crash.

Go to http://your fpp ip/settings.php#settings-system, press reset system, select everything, follow the instructions and set reconfigure fpp.  If that still causes it to crash, then reimage.  Avoid restoring any config backups.  Its likely something in one of your configs is upsetting fpp.

**Comment by brianbarrell** [comment]
I may try that.  But.....I downgraded to 7.5 on the same pi4 with the same config and with four plug-ins installed and it works great.Not totally convinced it is a config issue since it works on 7.5..I may push it back to 8.x and see if the problem comes back.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: darylc ***@***.***> Date: 6/15/24  6:09 AM  (GMT-06:00) To: FalconChristmas/fpp ***@***.***> Cc: brianbarrell ***@***.***>, Manual ***@***.***> Subject: Re: [FalconChristmas/fpp] Caught Signal 15 (Issue #1850) 
I'd suggest doing a system reset then, as there is nothing in the logs to give any information about the cause of the crash.
Go to http://your fpp ip/settings.php#settings-system, press reset system, select everything, follow the instructions and set reconfigure fpp.  If that still causes it to crash, then reimage.  Avoid restoring any config backups.  Its likely something in one of your configs is upsetting fpp.
