### ISSUE TITLE
FPP 8.x Crash File

### ISSUE THREAD

**Issue by bobreese** [FalconChristmas/fpp#1867]
While attempting to get my touchscreen working to display pictures in Remote mode on my Pi4, FPP 8 crashed and created a crash log.
I am including that log along with the standard logs.
[fpp-8.x_crash.zip](https://github.com/user-attachments/files/16074132/fpp-8.x_crash.zip)
[FPP_Logs_20240702.2046.zip](https://github.com/user-attachments/files/16074133/FPP_Logs_20240702.2046.zip)

**Comment by patdelaney** [comment]
@bobreese I think you we are missing some key information in how to reproduce this issue. Can you also include the information below, If we can reliably reproduce the issue, the likelyhood of it getting fixed is greater.  We need to be able to setup our environemnt to replicate what you are reporting, When you say touchscreen, are you referring to a Pi in Kiosk mode?

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**: 
A clear and concise description of what you expected to happen and why.

**Comment by darylc** [comment]
closed due to no response
