### ISSUE TITLE
Enhancement? Can a "Disable HDMI Port" be added?

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#187]
Due to the known conflict on the BBB (from an Adafruit article) between the HDMI ground plane and small USB Wireless dongles like the Edimax, can there be an easy method to enable/disable the HDMI port?

The two fixes listed on Adafruit are to use an USB Extender cable (working for me) or to disable HDMI.
Since the two ports (USB and HDMI) are so close, the HDMI can cause the wireless to disconnect.

**Comment by cpinkham** [comment]
FPP already disables HDMI on the BBB since it conflicts with both the Octoscroller and F16-B/F4-B Channel Outputs.  This appears to be due to the ground plane and small antenna on the Edimax, so closing ticket for now unless someone finds that it is not related to the ground plane and finds a way to disable the HDMI output even further.

I would like to make it an option to enable/disable HDMI, but that should be under another enhancement ticket.
