### ISSUE TITLE
Script added to FPP

### ISSUE THREAD

**Issue by bobreese** [FalconChristmas/fpp#1930]
I have a script called TouchscreenAsButton I would like added to the Script repository.
I validated it works in all versions of 7 and current version of 8.
[TouchscreenAsButton.zip](https://github.com/user-attachments/files/16747625/TouchscreenAsButton.zip)
@dkulp

**Comment by bobreese** [comment]
This works and I use it. I am working on a video to explain how to set it up and use it.
Also, I have been and still are using the script PlayEffectWhenNotPlayingFSEQ.sh 
It does work under V8
Please move it from untested to working.
It is another part of the scripts needed for my Sleigh Touchscreen.

**Comment by darylc** [comment]
@bobreese The FPP script repository is being phased out in general.  FPP can still run scripts, but FPP won't curate or distribute scripts.  This is for a few reasons.  1) No-one is willing to own the scripts, test, maintain, support them etc.  2) The script repository was created in a time before FPP commands and FPP plugins.  They have a much better support model - FPP commands are supported by the main FPP devs and the plugins are supported and verified before each major version by the plugin authors.

In the case of TouchScreenAsButton, this is best suited to a plugin.

As to PlayeffectWhenNotPlayingFSEQ, that has been removed because it is replaced by native functionality.  In this case if you name an effect background.eseq, FPP automatically plays it when it starts.  And if you enable this option, FPP will stop it from playing when an fseq is playing and start it again when the fseq stops:
![image](https://github.com/user-attachments/assets/cde695eb-708b-43d4-8beb-177ae82075d3)

**Comment by bobreese** [comment]
"In the case of TouchScreenAsButton, this is best suited to a plugin."
This was created by Mr. Kulp back in 2022 when I had issues making the touchscreen work.
I did not make it, I have tested it with each version since 5.5.
