### ISSUE TITLE
Command Presets and Restart FPPD - V8

### ISSUE THREAD

**Issue by bobreese** [FalconChristmas/fpp#1942]
Restarts of FPPD (manually or an FPP Update), causes a script in command presets to start a second script.
The more times you restart FPPD, the more times another script is started.

Preset Name: FPPD_STARTED
FPPD Command: Run Script

root      1686  1655  0 06:54 ?        00:00:00  \_ /bin/bash /home/fpp/media/scripts/TouchscreenAsButton.sh
root      1704  1686  0 06:54 ?        00:00:00  |   \_ sudo evtest /dev/input/event5
root      1706  1704  0 06:54 ?        00:00:00  |   |   \_ evtest /dev/input/event5
root      1705  1686  0 06:54 ?        00:00:00  |   \_ /bin/bash /home/fpp/media/scripts/TouchscreenAsButton.sh
root      9453  1655  0 07:27 ?        00:00:00  \_ /bin/bash /home/fpp/media/scripts/TouchscreenAsButton.sh
root      9471  9453  0 07:27 ?        00:00:00      \_ sudo evtest /dev/input/event5
root      9473  9471  0 07:27 ?        00:00:00      |   \_ evtest /dev/input/event5
root      9472  9453  0 07:27 ?        00:00:00      \_ /bin/bash /home/fpp/media/scripts/TouchscreenAsButton.sh

Only a reboot or manually Stop FPPD and Start FPPD clears the added processes.

**Comment by darylc** [comment]
Hi @bobreese 

This is expected behavior.  In most instances the restart fppd button in the UI does what is called a quick restart, with the aim to get fpp up and running again ASAP.  As you've noticed, to do it quickly it takes some shortcuts and so has different behavious than stop fppd and start fppd.

A couple of ways you could work around this:
a) change the script to handle this (eg check if its already running and exit if it is, or kill off the old one etc)
b) avoid using the restart fppd button and use stop/start instead

**Comment by darylc** [comment]
Note, this is not new to FPP 8, you would have experienced it in FPP 7 etc.

**Comment by dkulp** [comment]
Note:  the other option would be to create a "UserCallbackHook.sh" script that starts your script when passed the "preStart" or "postStart" argument.
