### ISSUE TITLE
FPP 8 with Microcyb capes always shows low power warning

### ISSUE THREAD

**Issue by jnealand** [FalconChristmas/fpp#1978]
I upgraded two Pis (a 3B and a 4b) from 7.5 to 8.  latest as of today.  Both units have Microcyb M4-Pi capes.  Each unit is powered by a Meanwell LRS-100-12 and worked fine under 7.5 with no warnings or issues noted.  Now both units show a low power warning.  They still seem to work fine - they are only on my workbench with one string of lights attached for testing.  Something changed in the FPP checks for power with FPP 8 since no warnings occurred in FPP 7.5 and the Pis are the only devices connected to the Meanwells.  The warning comes up even with NO lights even physically connected to the capes.  I can even turn on 1000 seeds from one port in testing so i know there is not a power issue with either meanwell.

**Comment by Poporacer** [comment]
FPP 8 included additional testing for Pi low voltage warnings. The pi's broadcast 2 error messages in regard to low voltage. One is that low voltage occurred since boot up, and the other is that there is low voltage now. The error you are seeing is the one that means that it happened at some point and is common on the initial power on phase. I have seen some buck convertors that can't output the correct voltage or can't handle the load. Try rebooting and see if it goes away. If the Pi is experiencing low voltage right now, it will show a lightning bolt. 
There was some additional code added to clear up this historical message, but there is some benefit to seeing that you had low voltage "at some point".

**Comment by cybercop23** [comment]
"fixed" in master branch. One and done doesn't constitute a big issue. Now, it will only do it if it has repeat issues. I'm sure the same was happening before but it wasn't logged.
https://github.com/FalconChristmas/fpp/commit/afebeef134a74c0904052a0cb85bfc252d1fc06c
