### ISSUE TITLE
FPPMon: Pi becomes unresponsive

### ISSUE THREAD

**Issue by McCoyCOREUSA** [FalconChristmas/fpp#1994]
8.1 version e444786

This version is running, but becomes unresponsive after a while. No crash on the Pi screen. Just all of a sudden no communication with FPP. I have to physically power-cycle the Pi. I have multiple Pi units and it's happening on all of them on this version.

NOTE: I can't ZIP get my logs. Returns error: 
Fatal error: Uncaught Error: Class "ZipArchive" not found in /opt/fpp/www/api/controllers/files.php:562 Stack trace: #0 /opt/fpp/www/api/lib/limonade.php(430): GetZipDir() #1 /opt/fpp/www/api/index.php(189): run() #2 {main} thrown in /opt/fpp/www/api/controllers/files.php on line 562

[fppd.log](https://github.com/user-attachments/files/17337182/fppd.log)
[apache2-error.log](https://github.com/user-attachments/files/17337184/apache2-error.log)

**Comment by ghormann** [comment]
1) The zip issue is a known issue and will be fixed in FPP 8.2. 
2) The logs don't get much detail.   Any chance you have multiple eithernet adapters (maybe wired and wireless?)    
3) When you say "No crash on the pi screen" you mean the monitor? Any chance you can put a keyboard on it and see if your network is still working (able to ping 8.8.8.8 or something).

**Comment by McCoyCOREUSA** [comment]
Update - DarylC suggested removing the FPP Remote Monitoring plugin. I removed it and it has been working properly since.

**Comment by darylc** [comment]
Please log this against the plugin github, since FPPMon plugin is a shared library there is nothing FPP can do to prevent it from crashing fppd. https://github.com/KulpLights/fpp-FPPMon
