### ISSUE TITLE
FPP_Install.sh support for Wireless Networking

### ISSUE THREAD

**Issue by jcochran** [FalconChristmas/fpp#211]
I have a few more modifications for FPP_Install.sh to support the work I've been doing on the "advanced" networking functionality. Can you please add the "dnsmasq" package to the install and disable "ifplugd", "dhcpcd", "udhcpd", and "dnsmasq" services if not already disabled. For sure, "dnsmasq" will need to be disabled.

**Comment by cpinkham** [comment]
Going to close this ticket since the networking configuration in FPP underwent major changes as we moved from Stretch to Buster.  A lot of what used to be in this advanced networking patch has now been rolled into FPP core, including WiFi hotspot support, so this ticket is probably not needed anymore.
