### ISSUE TITLE
Enhancement: Sync time from RTC periodically

### ISSUE THREAD

**Issue by Materdaddy** [FalconChristmas/fpp#218]
When an RTC is used, we only sync the time once at boot.  Pis with noticeable drift need to be synced without a reboot.  We should add a cronjob or something to accomplish this on a more frequent period (every day? hour?)

**Comment by Materdaddy** [comment]
http://diychristmas.org/vb1/showthread.php?4129-KombyPiRTC-2015-Group-Buy&p=67867#post67867

**Comment by cpinkham** [comment]
To begin with, I would do it in the middle of the night once per day.  If we try to do it once per hour, then we will have to put a bit of intelligence into it because it could cause us to skip a scheduled playlist if we jump forward and the playlist is not set to repeat.  We may have to code some additional logic into fppd to handle jumps forward in time.

**Comment by darylc** [comment]
The FPP development team met and decided that this issue is no longer relevant given all the changes to NTP in FPP since 2016.
