### ISSUE TITLE
/etc/issue not updated on upgrade

### ISSUE THREAD

**Issue by bigwavedave42** [FalconChristmas/fpp#222]
I did a fresh install of v1.5, followed by an upgrade to v1.8.  At console it shows "Falcon Player OS Image v1.5", as it would:
```
# cat /etc/issue
Raspbian GNU/Linux 7

Falcon Player OS Image v1.5
```
Now, this might be working as intended.  Technically it was installed with a v1.5 image, but it has had patches to v1.8.  If this is WAI, then that is totally fine.  I'm not sure if there is an intention for this to be updated on upgrades as well.  I think most people rely on the web interface to discuss the version they are running, and that would reflect the v1.8.

**Comment by cpinkham** [comment]
This is by design.  The OS Image is v1.5, but FPP is v1.8.  When we release FPP v2.0, there will be a v2.0 OS image, but we don't plan on releasing another OS image until FPP v3.0.  When a user upgrades FPP versions, it does not change the OS image version so we can see where the image started at.  FPP v1.5 and up won't work on a FPP v1.0 OS image without manual intervention and the upgrade scripts that are in the FPP repository aren't designed to handle the needed upgrades.  The same will be true for FPP v2.0, it will require a FPP v2.0 OS image and won't work on a v1.5 image without manual changes.

This also why I put "Falcon Player OS Image v1.5" in the issue file instead of "Falcon Player v1.5".

We also have both versions printed in the UI on the about page, here's a sample from one of my Pi's:

Version Info:
FPP Version:	v1.8-3-g98d41d1
FPP OS Build:	v1.5

That tells us is a user is trying to run FPP v1.8 on a FPP v1.0 OS image or on a Beta image like this from one of my BBB's. :)

Version Info	 
FPP Version:	v1.5-stage-484-gbcb336e
FPP OS Build:	v1.5-Beta
