### ISSUE TITLE
Using Help / SSH Shell - window background shifts

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#242]
When using the SSH Shell (instead of putty), I consistently get alternating White then Black background screens in Google Chrome.

Both work, but the White background makes some ANSI characters invisible.
If I get a white screen, I then close that window and get another one. It will be Black

Can it be always Black?

In Microsoft Edge browser, it won't even open the SSH Shell

**Comment by cpinkham** [comment]
I'm not sure why this was shifting 3 years ago, but you can right-click to bring up the ShellInABox menu and select 'White on Black' to get the black background.  I'm going to close this for now since it is user-selectable and some prefer white, some black...  This may have also been fixed when we upgrade ShellInABox along with the OS upgrade.
