### ISSUE TITLE
Email Support is Broken

### ISSUE THREAD

**Issue by jcochran** [FalconChristmas/fpp#267]
Email support is broken in the v1.8 image/baseline.

- The 1.8 image is missing the exim4 packages, as well as the command mail tools like mail/mailx.
- There is no trace of exim4/mail in the 1.8 install script to either install these packages or configure them post-install (e.g. setup the smtp.gmail.com smarthost for relay).
- I can find no other place which references exim, mail, or gmail outside of the GUI files so I don't think the missing files are being added/configured anywhere else.
- There is a bug on line 392 column 42 in common.php that prevents the FPP created aliases file from being copied to /etc (e.g. there's an extra period).
- The created aliases file still uses the original pi user and not the new fpp user (line 390).
- The chfn command (line 386) still uses the original pi user.

**Comment by jaredb7** [comment]
I can't verify but I think it was broken since 1.6 / 1.7?
I did a patch up for this for my show last year because really I needed email notifications for remote monitoring (show operated 20mins drive away). 

The only change I did to common.php was line 386 as you noted replaced pi with fpp for the finger name. It still writes the the aliases file even though there is a extra period in the path.

**Comment by patdelaney** [comment]
This still appears to be broken in master and 1.9

**Comment by cpinkham** [comment]
Closing, the indicated pull request has been applied to master and master-v1.x and will be merged into a release version as soon as it has a little wider testing.
