### ISSUE TITLE
1.9 Looping Sequence stops running when you cross midnight Saturday to Sunday

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#274]
I can easily reproduce this issue. It happens in current version of 1.9.
It only happens crossing over Saturday night, not any other day.

Pat

**Comment by patdelaney** [comment]
[fppd.txt](https://github.com/FalconChristmas/fpp/files/971009/fppd.txt)

Ran another test, when it hits midnight, a command is sent to shutdown gracefully. I have attached the log.

**Comment by cpinkham** [comment]
This is due to the WeeklySeconds method which the scheduler uses which rolls over at midnight Saturday.  This will likely not get resolved until the Scheduler code is refactored.

Closing for now since this fix will be part of a much larger rewrite which will include the ability to schedule across midnight boundaries.  The above issue is with a manually scheduled playlist.
