### ISSUE TITLE
MPG123 does not stop when restart FPPD causes FPPD to not be able to be restarted

### ISSUE THREAD

**Issue by LightsOnHudson** [FalconChristmas/fpp#294]
I had a playlist running, I made a selection in the multisync area to add a remote to the list to be controlled. The pop up told me i needed to restart fppd. I did, FPPD would not restart. Looking at 'ps aux' it showed that mpg123 was playing a mp3 file. 
I kill the MPG123 process. and FPPD will then restart when i say restart/start FPPD.

**Comment by cpinkham** [comment]
As part of fixing this, we need to ensure that all open file handles are closed in the child after we fork().  We should create a wrapper for fork() and replace all existing occurrences of fork() with our wrapper.

**Comment by cpinkham** [comment]
This should have been fixed by cfc8d7e0a6a, we now close all open file handles when we fork().  If the original mpg123 problem still occurs on the new Raspbian Stretch SD image, it can be reinvestigated.  All media outputs that spawn child processes should kill the child process if their Stop() function/method is called.
