### ISSUE TITLE
 http://www.usno.navy.mil/cgi-bin/time.pl is down and causing timeout issues on startup

### ISSUE THREAD

**Issue by rudybrian** [FalconChristmas/fpp#296]
http://www.usno.navy.mil/cgi-bin/time.pl is currently timing out which is causing issues with  checkTimeAgainstUSNO() which is called on startup.

**Comment by ghormann** [comment]
Since ntpd is part of the base image, shouldn't this just be changed to "ntpd -gq" ?  This will force time update no mater what which should be fine for a boot up sequence.   Process would be
1) Confirm network is up
2) make sure that ntp service is stopped
3) ntpd -gq
4) start ntpd service if down.

If aligned, with the design, I can work on a patch.  Just not sure which branch to submit it against.  master-v1.x?

**Comment by cpinkham** [comment]
The reason this uses HTTP is because some FPP users are behind firewalls that don't allow NTP outbound.  If you can think of a better way, or want to submit a patch that times out quicker, please do so.

**Comment by ghormann** [comment]
I had not considered the firewall...

**Comment by rudybrian** [comment]
The USNO site came back up some time after this was reported so we can probably close this. The only area for enhancement that I could see would to be more tolerant to future USNO site outages. Perhaps adding `--max-time 10` to the curl command in checkTimeAgainstUSNO() and bailing out if USNOSECS returns an error.
