### ISSUE TITLE
Background Sequences

### ISSUE THREAD

**Issue by Materdaddy** [FalconChristmas/fpp#30]
There has been a forum request for background sequences:

http://falconchristmas.com/forum/index.php/topic,326.0.html

**Comment by cpinkham** [comment]
Background effects sequences are now possible by using either a background.eseq sequence which is auto-started or by starting a looping effect sequence.  Multiple looping effect sequences can be started at the same time and they will each loop until stopped.   Closing the ticket for now since I think these additions from a few weeks ago satisfy the requested features.  The other scheduler/playlist enhancements are more involved and feature-rich.
