### ISSUE TITLE
v2.x  FPP UI does not recognize (read in v1.x gpio settings after upgrade) 

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#388]
This is could be part of the upgrade script. But after the upgrade of an existing system. GPIOs that were configure in 1.x are not displayed in the 2.x GPIO Web Gui.

If we can't get to it we should release note it.

**Comment by jaredb7** [comment]
Would be nice to do this and the universes. It would probably be a good idea do all the output types like Renard, DMX, LOR because if I recall correctly they were all in the same settings file. 

Being able to convert the Universe setup from v1 would be handy.

I'll see if I can investigate it at some stage, most probably show up post v2.1 though.

**Comment by cpinkham** [comment]
Closing this ticket since we are now on FPP v3.x and the GPIO screen has also recently undergone a major change to convert it to using FPP Commands instead of events.  Universes are also easier to setup now that we can output multiple universes per line, so the need for this may have changed.  If implemented, it would possibly be good to roll this into the backup/restore screen to allow restoring and auto converting from old FPP versions.
