### ISSUE TITLE
Cheap dsp pll has thrumbing in audio via usd cable in v2.0alpha.

### ISSUE THREAD

**Issue by aknflyer** [FalconChristmas/fpp#403]
upgraded to latest version

:

FPP Version: | v2.x-master-656-g0bb7e5c7
-- | --
FPP OS Build: | v2.0alpha
OS Version: | Raspbian GNU/Linux 9 (stretch)
Kernel Version: | 4.14.52-v7+

The sequence plays normally but my cheap Dsp Pll transmitter has thrumbing in the audio. It is conneced via the usd cable. Not the audio jack. No noise is being radiated into the system. Changing positions or shielding the cable has no effect.
[Thrumbing.zip](https://github.com/FalconChristmas/fpp/files/2317065/Thrumbing.zip)
[FPP_Logs_20180824.0507.zip](https://github.com/FalconChristmas/fpp/files/2317091/FPP_Logs_20180824.0507.zip)

**Comment by darylerwin** [comment]
Add me to the list .. worked just fine in 1.10 but now the song is covered in heavy static..

**Comment by darylerwin** [comment]
ps played you audio -- yep thrumbing .. whatever that is .. same here..

**Comment by Geoff-Ilmax** [comment]
I can also confirm that this issue is present with the VAST FMT-212R Transmitters.  I have tested a clean install of 2.4, and upgraded it to 2.5.2 with the same results.  Any USB transmitter that I use has this issue.  Current workaround is to use legacy audio processor in FPP Settings.

I have a dedicated PI/transmitter that I can gather/test with this is not part of my show.

**Comment by cpinkham** [comment]
The new SDL audio output has been updated significantly this year and has been the default now for quite a while.  I don't believe we received any notices of issues like this during this past season with FPP v3.5.x.  It worked great with my VAST-FMT212R connected via USB.  Closing this ticket.
