### ISSUE TITLE
Create development environment instructions and contribution guidelines. 

### ISSUE THREAD

**Issue by gerryhernandez** [FalconChristmas/fpp#471]
I would consider this a pseudo-enhancement, I suppose... Anyhow, I'd like to contribute bug fixes and enhancements, but ramp-up time to figure out a local dev environment for FPP is pretty steep if you don't know where to start. I'm requesting a guide to get a local dev environment set up for working on the FPP project. I thought I had read somewhere that there's a VM image or something that's used for development, but I can't find it. What better place to put it than right here in the repository?

Things of note:
- Runtime environment (VM, Docker, or directly on the host OS)
- Toolchains and versions (CMake, Clang, libraries, etc)
- Suggested editors, settings, scripts, etc
- Anything else that seems important

@dkulp - a description of your setup would be an amazing time saver.

As an aside to that, I'm also requesting contribution guidelines, even if they're minimal and preliminary.

Thanks!

**Comment by dkulp** [comment]
I'd love to see a Docker image as well. :)     Seriously, my entire dev environment for all my FPP work consists of exporting /opt from my BBB or Pi (update /etc/samba/smb.conf to export /opt with force user = root) and mounting that from my Mac to use a better editor, but all the compiling and stuff is done on the BBB and/or Pi.  I ssh in and "sudo bash" and just compile (make optimized) and do all the git commands and such directly there.

**Comment by dkulp** [comment]
One other note: from /opt/fpp/src, you can run fppd directly in the foreground via:

On BBB: just run "./fppd -f"

On Pi: you need to do an "export LD_LIBRARY_PATH=/opt/fpp/external/RF24" first, then the "./fppd -f" will work.      At some point, I keep thinking about making that a static library that we just link in, but it hasn't been critical and it seems to work OK.  Either that or install it in /usr/local/lib or something.

**Comment by jeffla** [comment]
I'm guessing the architecture would have to change a little to dockerize it due to media playback and possibly other dependencies. But if we're voting, I'll add another for Docker.

**Comment by gerryhernandez** [comment]
Can we list out platform-specific tools and capabilities? For example, OMXPlayer is for Raspberry Pi, I'm assuming GPIO is different on BBB versus Pi (I don't have one, sorry), etc? A ready to go environment will be closer to an analog, rather than full virtualization, so I'd like a general idea as to where to draw the abstraction lines.

My initial thought is something along the lines of Docker or Vagrant. Something that can be destroyed and rebuilt quickly, easily, and in a version-controlled way, reproducible on most people's machines. One interesting advantage of Vagrant is that we could use QEMU as the backend to virtualize an ARM machine, potentially getting us a bit closer to a "real" Pi. It may or may not be worth it, just thought I'd mention it.

Looks like we have some interest. I'll try to put some time toward an out-of-the-box development solution, but I won't really have any time until maybe after Christmas.

**Comment by gerryhernandez** [comment]
@cpinkham - I'm not sure how I can PM you. I'd love to be added to a development forum, if we have one. Do we have a Slack, Discord, or any other type of chatroom?

More immediately, I have a few questions before I make a pull request for fixing #478 that would just be a simple conversation. I suppose I could ask in the issue, but it's not really an issue... it has more to do with how the FPP upgrade scripts already work. A forum or chatroom would be perfect for these types of questions, methinks.

**Comment by cpinkham** [comment]
I made a change on the forum which should give you access to the
Developer area.  If you scroll down to the bottom of the forum list,
you should see a new Developer item at the bottom.  We do have a Slack,
but it is rarely used.  I had to reset my password to login because it
has been so long.  I am logged in now though, so feel free to use it as
well for quick questions.

On Tue, 2018-12-11 at 08:55 -0800, Gerry Hernandez wrote:
> > > @cpinkham - I'm not sure how I can PM you. I'd love to be added to a
development forum, if we have one. Do we have a Slack, Discord, or
any other type of chatroom?
> > > > > More immediately, I have a few questions before I make a pull request
for fixing #478 that would just be a simple conversation. I suppose I
could ask in the issue, but it's not really an issue... it has more
to do with how the FPP upgrade scripts already work. A forum or
chatroom would be perfect for these types of questions, methinks.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> > > > > > > > > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/FalconChr
istmas/fpp","title":"FalconChristmas/fpp","subtitle":"GitHub
repository","main_image_url":"https://assets-cdn.github.com/images/em
ail/message_cards/header.png","avatar_image_url":"https://assets-
cdn.github.com/images/email/message_cards/avatar.png","action":{"name
":"Open in
GitHub","url":"https://github.com/FalconChristmas/fpp"}},"updates":{"
snippets":[{"icon":"PERSON","message":"@gerryhernandez in #471:
@cpinkham - I'm not sure how I can PM you. I'd love to be added to a
development forum, if we have one. Do we have a Slack, Discord, or
any other type of chatroom?\r\n\r\nMore immediately, I have a few
questions before I make a pull request for fixing #478 that would
just be a simple conversation. I suppose I could ask in the issue,
but it's not really an issue... it has more to do with how the FPP
upgrade scripts already work. A forum or chatroom would be perfect
for these types of questions, methinks."}],"action":{"name":"View
Issue","url":"https://github.com/FalconChristmas/fpp/issues/471#issue
comment-446277106"}}}
> [
> {
> > "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> > "target": "https://github.com/FalconChristmas/fpp/issues/471#issuecom
ment-446277106",
> > "url": "https://github.com/FalconChristmas/fpp/issues/471#issuecommen
t-446277106",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> > "url": "https://github.com"
> }
> },
> {
> "@type": "MessageCard",
> > "@context": "http://schema.org/extensions",
> "hideOriginalBody": "false",
> "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
> > "title": "Re: [FalconChristmas/fpp] Create development environment
instructions and contribution guidelines.  (#471)",
> "sections": [
> {
> "text": "",
> "activityTitle": "**Gerry Hernandez**",
> > "activityImage": "https://assets-cdn.github.com/images/email/message_
cards/avatar.png",
> "activitySubtitle": "@gerryhernandez",
> "facts": [
> 
> ]
> }
> ],
> "potentialAction": [
> {
> "name": "Add a comment",
> "@type": "ActionCard",
> "inputs": [
> {
> "isMultiLine": true,
> "@type": "TextInput",
> "id": "IssueComment",
> "isRequired": false
> }
> ],
> "actions": [
> {
> "name": "Comment",
> "@type": "HttpPOST",
> > "target": "https://api.github.com",
> > > > "body": "{\n\"commandName\":
\"IssueComment\",\n\"repositoryFullName\":
\"FalconChristmas/fpp\",\n\"issueId\": 471,\n\"IssueComment\":
\"{{IssueComment.value}}\"\n}"
> }
> ]
> },
> {
> "name": "Close issue",
> "@type": "HttpPOST",
> > "target": "https://api.github.com",
> > "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\":
\"FalconChristmas/fpp\",\n\"issueId\": 471\n}"
> },
> {
> "targets": [
> {
> "os": "default",
> > "uri": "https://github.com/FalconChristmas/fpp/issues/471#issuecommen
t-446277106"
> }
> ],
> "@type": "OpenUri",
> "name": "View on GitHub"
> },
> {
> "name": "Unsubscribe",
> "@type": "HttpPOST",
> > "target": "https://api.github.com",
> > "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\":
418452020\n}"
> }
> ],
> "themeColor": "26292E"
> }
> ]

**Comment by LightsOnHudson** [comment]
FPP Slack channel? We use slack. Chris, how would I add yoU?

**Comment by DMXMax** [comment]
> FPP Slack channel? We use slack. Chris, how would I add yoU?

Late to the party. If we have a slack, I'd be interested as well.  I also don't see the developer area on the fpp forums.

**Comment by ghormann** [comment]
Closing.   Docker option exists now and /SD/FPP_Install.sh is decent and setting up environment in a Debian environment.
