### ISSUE TITLE
Offset problem with virtual matrix

### ISSUE THREAD

**Issue by thisim** [FalconChristmas/fpp#473]
Hello, I use a 60 "LCD TV as a virtual matrix, there is a gap between the time when the LEDs of my house light up and the lighting of the virtual matrix.
I use FPP 2.5.
The TV has an offset due to the image processing of the TV.
Would it be possible to add an option to be able to add a positive or negative offset so that the video of the virtual matrices is called exactly like the leds.
I made a short video where we can see the offset.

https://youtu.be/EdrnChwST-o

Sorry for my english (i'm french).

**Comment by cpinkham** [comment]
If the Virtual Matrix is running on a dedicated Remote Pi, then you can
go to the Advanced Settings page and adjust the "Remote Media/Sequence
Offset" to shift the remote slightly ahead/behind the main playback
from the master.

On Tue, 2018-12-04 at 10:27 +0000, thisim wrote:
> > > Hello, I use a 60 "LCD TV as a virtual matrix, there is a gap between
the time when the LEDs of my house light up and the lighting of the
matrix.
> 
> The TV has an offset due to the image processing of the TV.
> 
> > > Would it be possible to add an option to be able to add a positive or
negative offset so that the video of the virtual matrices is called
exactly like the leds.
> 
> I made a short video where we can see the deceleration.
> https://youtu.be/EdrnChwST-o
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/FalconChr
istmas/fpp","title":"FalconChristmas/fpp","subtitle":"GitHub
repository","main_image_url":"https://assets-cdn.github.com/images/em
ail/message_cards/header.png","avatar_image_url":"https://assets-
cdn.github.com/images/email/message_cards/avatar.png","action":{"name
":"Open in
GitHub","url":"https://github.com/FalconChristmas/fpp"}},"updates":{"
snippets":[{"icon":"DESCRIPTION","message":"Offset problem with
virtual matrix (#473)"}],"action":{"name":"View
Issue","url":"https://github.com/FalconChristmas/fpp/issues/473"}}}
> [
> {
> > "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> > "target": "https://github.com/FalconChristmas/fpp/issues/473",
> > "url": "https://github.com/FalconChristmas/fpp/issues/473",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> > "url": "https://github.com"
> }
> },
> {
> "@type": "MessageCard",
> > "@context": "http://schema.org/extensions",
> "hideOriginalBody": "false",
> "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
> "title": "Offset problem with virtual matrix (#473)",
> "sections": [
> {
> "text": "",
> "activityTitle": "**thisim**",
> > "activityImage": "https://assets-cdn.github.com/images/email/message_
cards/avatar.png",
> "activitySubtitle": "@thisim",
> "facts": [
> {
> "name": "Repository: ",
> "value": "FalconChristmas/fpp"
> },
> {
> "name": "Issue #: ",
> "value": 473
> }
> ]
> }
> ],
> "potentialAction": [
> {
> "name": "Add a comment",
> "@type": "ActionCard",
> "inputs": [
> {
> "isMultiLine": true,
> "@type": "TextInput",
> "id": "IssueComment",
> "isRequired": false
> }
> ],
> "actions": [
> {
> "name": "Comment",
> "@type": "HttpPOST",
> > "target": "https://api.github.com",
> > > > "body": "{\n\"commandName\":
\"IssueComment\",\n\"repositoryFullName\":
\"FalconChristmas/fpp\",\n\"issueId\": 473,\n\"IssueComment\":
\"{{IssueComment.value}}\"\n}"
> }
> ]
> },
> {
> "name": "Close issue",
> "@type": "HttpPOST",
> > "target": "https://api.github.com",
> > "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\":
\"FalconChristmas/fpp\",\n\"issueId\": 473\n}"
> },
> {
> "targets": [
> {
> "os": "default",
> > "uri": "https://github.com/FalconChristmas/fpp/issues/473"
> }
> ],
> "@type": "OpenUri",
> "name": "View on GitHub"
> },
> {
> "name": "Unsubscribe",
> "@type": "HttpPOST",
> > "target": "https://api.github.com",
> > "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\":
419522394\n}"
> }
> ],
> "themeColor": "26292E"
> }
> ]

**Comment by thisim** [comment]
My virtual matrix is ​​of course a slave pi. I have already tried to change this setting to positive or negative and it does not change anything. The setting is not just for shifting the soundtrack relative to the sequence. In fact it would be necessary that my sequence on the slave pi starts before the soundtrack and the sequence of the master pi. The ideal will be to have this setting just for the video output hdmi of the virtual matrix. This will make it possible to use the virtual matrix also on the master pi.

**Comment by cpinkham** [comment]
I believe this was addressed on the forum.  If not, it should be taken there.
