### ISSUE TITLE
ETH0 and ETH1 swapping, "rename4" device appearing

### ISSUE THREAD

**Issue by LightsOnHudson** [FalconChristmas/fpp#593]
I have ETH0 - hard line into my show network. I'm accessing it fine. I plug in a USB ethernet adapter for the Colorlight network. I reboot. ETH1 is now ETH0 and vice versa. 

I pull the USB adapter out, reboot, eth0 is back with the proper DHCP address.

I click CREATE Persistent names, reboot.

I see ETH0 still has the right IP address. 

I plug in the USB adapter.  a device called RENAME4 appears. And It has my DHCP IP address. 

How do I get ETH0 - Hard line DHCP and ETH1 - DHCP (because it will be on my color light network) to work . 

I'm running 3.5.1... 3.5.2... Master.. All do the same thing. 
![Screen Shot 2019-11-17 at 8 51 24 PM](https://user-images.githubusercontent.com/10136122/69023568-731b8700-097c-11ea-9184-7e77945fa5a5.png)

**Comment by dkulp** [comment]
Again, not an issue to be logged here.   Post in forums.   This is working as per expectations.   When you created the persistent names, only eth0 was available so that is the only one assigned a name.   After reboot with the other adapter, it likely was initially assigned eth0, but due to the persistent name on the internal adapter, it had to be renamed (thus the rename4) so that eth0 was available.    Clear the persistent names, boot without the USB so internal gets eth0, plug in USB, go to network page and click persistent at that point as both interfaces are now available.
