### ISSUE TITLE
Support FIFO output for Audio Player

### ISSUE THREAD

**Issue by edalquist** [FalconChristmas/fpp#598]
Would it be possible (or interest in a pull request) to have the audio output layer decide the ogg/mp3 to PCM and write it to a named pipe?

That would let us use something like https://github.com/badaix/snapcast to do network based audio distribution directly from the FPP Master.

**Comment by cpinkham** [comment]
If you are interested in pursuing this, please start a new thread for discussion on the FalconChristmas forum so we can discuss.  I do have some interest in this feature as well because I would like to have the ability to play audio in the web browser on the HTTP Virtual Display screen.  I think our preference would be to support this using the newer SDL media output, not ogg123/mpg123.  Dan may have some ideas on this already, but we should probably discuss before doing a lot of coding in a specific direction.  It would be nice if this audio data could be passed to a plugin as well and you could implement snapcast as a C++ plugin.

**Comment by edalquist** [comment]
Done: http://falconchristmas.com/forum/index.php/topic,12264.0.html

I'd be interested in helping out with this if you're looking for external contributions.
