### ISSUE TITLE
Add UI control of Connman parameters (PreferredTechnologies and AlwaysConnectedTechnologies)

### ISSUE THREAD

**Issue by Vlad-Star** [FalconChristmas/fpp#614]
Feature request. Please, add UI control (order and enable/disable checkbox) for the following Connman parameters (/etc/connman/main.conf)

PreferredTechnologies=ethernet,wifi
AlwaysConnectedTechnologies=ethernet,wifi

Manpage: http://manpages.ubuntu.com/manpages/cosmic/man5/connman.conf.5.html

Backstory: I have ethernet as a primary interface and wifi as a backup/management interface in the same VLAN, with different IP addresses assigned to them via DHCP. With the default setting of "PreferredTechnologies=wifi,ethernet" it tends to make a default route via wifi interface, which causes all kind of problems while playing the FSEQ sequences, due to wifi congestion. Ethernet interface should always be a default priority between two, when available. After switching the order (PreferredTechnologies=ethernet,wifi) and without AlwaysConnectedTechnologies variable, connman tends to leave only ethernet interface and skips wifi. I don't know if this would work for everyone though, that's why I am asking for a granular UI control for those.

**Comment by cpinkham** [comment]
Closing this since bullseye switched to networkd for network configuration.  One approach we have talked about in the past is creating a bridge interface that allows us to put eth0 and wlan0 on the same network with only a single IP address.  I don't know what that would take with networkd, but it may be the approach we take since it would also fix other issues users see when they put both interfaces on the same network.
