### ISSUE TITLE
README is missing critical setup information

### ISSUE THREAD

**Issue by rossmckelvie** [FalconChristmas/fpp#621]
I am new to FPP so hoping to get going by checking out the usage documentation. on README the wiki doesn't load for me, and the other is to a general forum link. Could installation & configuration instructions be added to the README file? There is a pinned thread at the top of the final link, that includes these instructions, but it's not even linked directly. Happy to open a PR to clean up the readme a little bit, at the very least include a [direct link](http://falconchristmas.com/forum/index.php/topic,9372.0.html) to the forums' instructions, unless there's a reason this information is purposely being omitted from README and linked instead?

**Comment by rossmckelvie** [comment]
I also noticed that only every other release recently doesn't include an .img asset, at least the latest and third latest. Are the compile from source instructions anywhere?

**Comment by nmiller0113** [comment]
https://falconchristmas.github.io/FPP_Manual.pdf is the current manual. I suggest going to the Falcon FPP Forums http://falconchristmas.com/forum/index.php/board,8.0.html for any other questions...Git is more for reporting issues.  As for the versions, the developers don't build image files for every one.  Just download the latest image available and update from within the UI.

**Comment by cpinkham** [comment]
If you want to create build and install docs for a specific Linux distribution, feel free to do so and submit a PR.  We run FPP on Raspbian, so that is our target distribution, but that means our FPP_Install.sh script also has a good chance of working on Debian.  FPP was originally designed to be an appliance although newer versions include support for running in docker.  The FPP_Install.sh script takes over the installed system since we do treat it as an appliance.  If you want to develop on a non-Pi/BBB system, you can hand-install the needed packages, compile fpp by going into the src directory and running 'make' and then running ./fppd.sh.

**Comment by cpinkham** [comment]
Closing ticket in anticipation of a PR at some point.
