### ISSUE TITLE
Add current playlist mqtt topic

### ISSUE THREAD

**Issue by thedannymullen** [FalconChristmas/fpp#702]
When I query the api @ http://fpp/api/fppd/status I get the current playlist as well as some other things.  

I am interested in the current playlist that is playing.  Similar to FPP/falcon/player/FPP/playlist/sequence/status topic except I would like to get the playlist selected in the player.  

Is this something that could be addedI?  

Reasoning is when I trigger the playlist in my home automation system I get the sequence that is running, but nowhere do I know if the correct playlist is running without actively opening the player.  I would like to display the playlist on the status page of my home automation.  Sometimes we have the same sequence is multiple playlists.  

Suggestion maybe add to FPP/falcon/player/FPP/status when playing say "playing playlistname".

**Comment by ghormann** [comment]
The current name of the playlist playing will be sent once when it starts via .../playlist/name/status 

In addition, you can configure MQTT to periodicially publish every xx seconds the current status via topic "playlist_details".   I like this version myself because if fppd dies, it stops publishing and I know something is wrong.   See:  https://github.com/FalconChristmas/fpp/blob/master/docs/MQTT.txt 

Don't these existing topics meet your needs @thedannymullen ?

**Comment by thedannymullen** [comment]
@ghormann  I will review the doc later today.  From your initial description I believe it does.  Full response after my review.
I assume this is version 4.0 you are discussing?  I ask because this is the version I have been using.

**Comment by ghormann** [comment]
Both were added  in 3.x and are support in 4.0 as well.

**Comment by thedannymullen** [comment]
This does work Thanks!!!  Closing the issue!
