### ISSUE TITLE
Going into Pixel Overlay Models is causing FPPD to stop and will not restart in  v4.x-master-329-gda99e531

### ISSUE THREAD

**Issue by vcuncg** [FalconChristmas/fpp#727]
I am using the Pixel Overlay Models and was able to go in and create a model and save it.  However, every time I go into the Pixel Overlay Models section after that, FPPD stops and will not restart without doing a power cycle on the Pi.  The reboot within the Pi will not work, so I power cycle to get it back up and running.  I have all the log files captured, so if there is one that might help with this, let me know and I can post it here.

**Comment by cpinkham** [comment]
Rather than using the Restart button in the UI, can you try using the
Start button and see if it acts any differently?  The Restart button
normally tries a fast restart if possible, but should fall back to a
stop/start if needed.  The issue could be in the fallback if fppd isn't
running to listen to the restart command.

**Comment by vcuncg** [comment]
Neither one worked last night.  I have uninstalled a number of the matrix plugins and the sms plugin today.  I rebooted and the error seems to have gone away.  For now I will close this and keep checking on my end to add the plugins back and try to drive down to what caused it.  If it returns I will open another issue.  Thanks for all the work on this software!
