### ISSUE TITLE
MultiSync Copy Files - No remotes configured and no list supplied.

### ISSUE THREAD

**Issue by brennja** [FalconChristmas/fpp#732]
FPP MultiSync shows Master and four Remote systems.
When I click Copy Files, I get the following error message:
"No remotes configured and no list supplied."

I have tried Send MultiSync to ALL remotes via Multicast, Send MultiSync to All remotes via Broadcast and both get the same error message. Unchecked both and also get the same error message.

**Comment by ghormann** [comment]
@brennja: What version of FPP on the master and remotes?

**Comment by brennja** [comment]
Sorry, should have included that information.
Master -  v4.x-master-338-g0ea606d9
Remotes -  v4.x-master-338-g0ea606d9 and 3.6.2-1-g8c761fbc

**Comment by cpinkham** [comment]
I know what is causing this and have a fix in mind, I just need to code/test.

**Comment by cpinkham** [comment]
The fix is going to take a bit more planning.  FPP v4.0 does not use Avahi anymore and that is what we were using to discover other FPP systems running in Remote mode.  I think that we need to update the syncRemotes.php script to use the list of Remotes found via FPP's MultiSync discovery if there are not remotes selected manually.

**Comment by cpinkham** [comment]
This should be fixed in the latest version as the Copy Files functionality has been moved to an action like the Upgrade FPP and Restart FPPD actions.  You can now select individual systems to receive files.
