### ISSUE TITLE
Help Pages are Missing 4.0-beta1

### ISSUE THREAD

**Issue by TechplexEngineer** [FalconChristmas/fpp#734]
This might be expected but it seems there are help pages missing.

Example one:
From the help index page (http://fpp.local/help.php) the settings bullet results in a modal that says "No help file exists for this page yet"

Example two:
From the settings page (http://fpp.local/settings.php) on the mqtt tab there is a link that says "For more info Press F1 for more details" pressing the F1 key on my keyboard or clicking the link both result in a modal that says "No help file exists for this page yet"

Is this expected behavior?

**Comment by cpinkham** [comment]
The main help.php page needs to have the settings link removed since there are more than one settings help pages now since there can be one help page per tab.  The settings.php page help page is a bug and I will take a look at that.  It was working to begin with since I made mods to allow the per-tab help, but it must have broken along the way somehow.
