### ISSUE TITLE
Enhancement:  fill in default DNS server when static IP address is selected

### ISSUE THREAD

**Issue by MarkA75160** [FalconChristmas/fpp#739]
A very common issue that comes up with new users when they set a Static IP address is they can't access github.com when attempting to update FPP or browse the Script Repository.  This is usually because selecting Static IP also changes the DNS selection to "Manual" with a blank Server.  If the user doesn't manually enter a valid DNS server then updates will not work.

This suggestion/enhancement would be to have FPP fill in a default DNS address when the user selects Static IP addressing.  It currently fills in default netmask and gateway values (which can be changed if needed).  This logic could also fill in a default DNS Server to match the gateway (most home gateways provide DNS proxy) or a well known public server (like 8.8.8.8 or 1.1.1.1). 

While these default values may not be appropriate for all scenarios, they would work in the vast majority of cases and help reduce a question/issue that has been recurring for years.  Of course these values could be overridden by the user if needed (similar to when the gateway is not the default .1 address) and having a common value that works for most users is better than a blank value that doesn't work at all.

**Comment by ghormann** [comment]
Good idea.  Implemented.

**Comment by cpinkham** [comment]
I think this patch needs a little bit more to be effective.  It currently only changes the value in the UI, it doesn't handle saving and applying the DNS config.  In order to do this programatically, I think we would need to add a bit of logic to see when we are OK to set the DNS manually.  We should really check both/all interfaces and if we are static-only, DNS should be set to Manual, but if we have any DHCP interfaces then DNS should be set to DHCP.  I'd like to auto detect this and change the radio buttons appropriately.  I thought about reworking this screen as part of the settings UI changes, but stopped myself due to feature creep.

For now, maybe the simplest way is add a popup or other onscreen warning when the user saves the static IP info (and has no static DNS set) informing them that they may need to set a DNS server if they are only using static IP(s).  The code can fill in the default DNS IPs but not flip the DNS radio button to Manual but point the user to do so if they are only using static.

**Comment by ghormann** [comment]
Yes, good point.

**Comment by MarkA75160** [comment]
I think there is a typo in the warning message...
""Don't forget to set a DNS IP address. Recommend using 8.8.8.8 **_is_** not sure"

I think you meant "**_if_** not sure"
