### ISSUE TITLE
HDMI out virtual matrix.

### ISSUE THREAD

**Issue by MaxJago93** [FalconChristmas/fpp#748]
option to make HDMI output pixel accurate? when 1 pixel is scaled to multiple it creates errors when running effects as they don't line up ect. I would like to send HDMI out to my sender card for my large P4.81 matrix screens but having this issue with fpp re scaling the HDMI out as such?

**Comment by dkulp** [comment]
Mostly an FYI:   FPP isn't doing the scaling, the Pi hardware is.     Doing anything other than the standard HDMI resolution and letting the hardware scale requires modification to the /boot/config.txt and a reboot which is not something we would be doing as part of any FPP settings/configuration due to such modification can easily cause the Pi to not boot at all.    If you want to experiment, you would need to read all the instructions at https://www.raspberrypi.org/documentation/configuration/config-txt/video.md

**Comment by MaxJago93** [comment]
Hi Daniel, thanks for explaining that to me makes sense now I will have to experiment and read that document.
would it be possible to get you guys to support P4.81 panels instead? then I will then just send direct to my Linsn receiver cards.  they are 52x52 dot 1/13 scan panels.

**Comment by dkulp** [comment]
Without access to panels to attempt, I'm not sure I would just blindly add the configs.   If you are adventurous, you can manually edit the /home/fpp/media/config/channeloutputs.json file and change the panelWidth, panelHeight, and panelScan settings.  It might "just work".   I don't know.   Especially with the Linsn's as I know nothing about them.

**Comment by MaxJago93** [comment]
Great thanks for the information I will most definitely attempt your suggestion if I’m unsuccessful Would you be happy for me to have a panel sent to you?

**Comment by cpinkham** [comment]
I will be looking at updating FPP’s Virtual Matrix code you allow it to be used with ColorLight and Linsn sender cards by setting the display resolution to a high native output and overlaying the Virtual Matrix on a sub portion of the frame.  Daryl is looking for this as well and we have exchanged a few messages on it.  I also want to look at adding a UI for the SubMatrix code which is already in fppd to allow you to have multiple matrices on one output.  This will be helpful with the sender cards since you could have multiple receivers on one sender with each receiver connected to a different matrix.

Chris

**Comment by MaxJago93** [comment]
Hi Chris, This is great news! you guys do an exceptional job! do you have a donations link?
I have spoke to Daryl about my setup as well.  Im running Linsn sender and receiver cards with P4.81 panels the screens are 12x6 panels so 624x312 pixels I have 2 in my display I wish to run each of a fpp device. 

Thanks for the help if you need any testing done ect don't hesitate to ask.

**Comment by patdelaney** [comment]
Chris I have Linsn and Colorlight Sender cards (1 of each) so I can help in
the testing effort.

Pat

**Comment by cpinkham** [comment]
I have the backend code working and will try to get something into git this week once I do a little more testing.  Then I need to think about and create a UI for creating the SubMatrices.  That shouldn't hold up testing though if you can hand-edit your /home/fpp/media/config/co-other.json file.  Once I push some code, I'll post an example config file here so you can test.

**Comment by MaxJago93** [comment]
Hi Chris,

Thank you very much for spending time on this for us! I look forward to being able to test it.

**Comment by MaxJago93** [comment]
Hi Chris, Just wondering how your going with this? My panels and send/receiver cards have arrived so I'm good to do any testing you may require.

**Comment by darylc** [comment]
I believe 2 changes are required:

1. Configure PI to stop scaling:
The default FPP config (/boot/config.txt) has overscan for the hdmi enabled. This means you don't get a true piexl for pixel representation. To fix this add disable_overscan=1 to the file and comment out the rest of the overscan_* settings and reboot your pi.

2. Change FBMatrix to stop scaling, I've been manually hacking this in each year based on some hints Captain Murdoch provided back in the circa FPP 1.5 days, I can share the code on request, but really its a butcher job so unlikely to be useful to the developer.

**Comment by darylc** [comment]
Probably also need an option as to what resolution is desired on the HDMI output

**Comment by dkulp** [comment]
The first part is now on master.   The Virtual Matrix has an option for scaling.  Default is hardware scaling (old behavior) but added a software scaling (which can help with certain monitors that have issues with the small modes) as well as a "none" which leaves the mode alone and just sticks it up in the upper left.    Thus, the VirtualMatrix changes should be OK now.   

The changes to /boot/config.txt are completely separate as those would need to be system settings in the settings panel.   They also scare me a bit as modifying anything in there can easily make the pi not boot.    I cannot make the disable_overscan=1 a default as that causes other issues with some monitors (mine cuts of a column).    Anyway, the VirtualMatrix changes are there, the rest is config stuff that is extremely dependent on the monitor/projector/sender card.

**Comment by darylc** [comment]
Thanks so much Dan.  I did a bunch of testing tonight, it's looking very promising.

Any chance you could add an option on how to set a x,y coord instead of assuming 0,0?  I've tried for a few hours to work out how to hack that into the code thinking I'd send you a pull request, but I don't understand the code enough :(

This is required to run multiple virtual matricies on the same frame buffer.

**Comment by dkulp** [comment]
Implemented now as long as Scaling is set to none.   You can have a bunch of VirtualMatrices on the same frame buffer device.
