### ISSUE TITLE
FPP 4.0.1 Scheduler not firing overlapping priority playlist

### ISSUE THREAD

**Issue by ryanm352** [FalconChristmas/fpp#754]
I have two playlists created, playlist #1 has an overlapping schedule of playlist #2. The playlist set to fire with priority of 1 never fires when the time is between the scheduled time. According to the docs, in this case, playlist #1 should fire between the times of 1:54am and 1:56am and continue to fire until that time period has lapsed. Each playlist contains a single "sequence only" option with 1 sequence 30 seconds long. 

![screenshot copy](https://user-images.githubusercontent.com/840461/86889053-c172c700-c0c0-11ea-9bf0-e10a1276463d.png)

As a work around, I had to create some complicated branches using time, but this work-around isn't feasible since there is a possibility that a branch might be missed if the previous sequence takes too long.

Update: The problem seems to be when the repeating playlist is set to a `hardstop.` It seems to constantly re-start the playlist over and over

**Comment by Poporacer** [comment]
I am not sure what documentation you are referring to? The FPP Manual does not mention anything about priorities. It does state:
"Then it will start at the scheduled start time if there is no other sequence currently
playing, or start when the currently playing sequence ends as long as it is within the
scheduled time frame."
Because you have a playlist that is playing "forever" then the playlist never ends so the next playlist will not start. Why not break your "forever" playlist to start at 00:00:00 and end at 01:53:59 with a hard stop (01:54:00 might work) and then add another playlist to start at 01:56:00 and end at 24:00:00 that sounds much simpler than a bunch of branches?

**Comment by ryanm352** [comment]
I'm looking at the 2.2 Manual from Feb. 2020 (p. 63) that says 
```
You can have multiple playlist for different days of the week or even different holidays. If you
have a playlist that is scheduled to play while another one is playing, the one with the highest
priority will play. The Playlist at the top of the list has a higher priority than the one below it.
You can drag a playlist in this screen to reorder it.
```

To me, this reads, stop whatever playlist is playing, then play the higher priority (even if the lower priority palylist is infinite). I'll have to add 16 different entries, agh! I just went ahead and re-factored the plugin system on fpp and made my own plugin to stop whatever playlist is the main playlist (sign) in the image above, then play a single random sequence from the halloween playlist, then resume the `sign` playlist. I was also able to get react up and running for my plugin, yay. I'll go ahead and close this out, but I think the documentation needs an update for clarification. 

Thanks!

**Comment by ryanm352** [comment]
Closing, suggesting manual update for clarification.

**Comment by Poporacer** [comment]
You are right, it does say that. I have no idea where that came from and I am the one that wrote it! It is already corrected in the next revision. Thanks for pointing it out.
