### ISSUE TITLE
FPP 4.0 Default Package Installation 

### ISSUE THREAD

**Issue by ryanm352** [FalconChristmas/fpp#755]
I'm working on a new scheduler plugin for a specialized sign and I was finally able to load react in my plugin's page, but I had to install a few packages that took a while to install on my pi zero. Can we get the following packages pre-installed with the image?

node (LTS)
npm
yarn
php-mbstring

This would definitely give me some incentive to create a fresh UI using modern tools. I'll be adding a PR to add some support for better file handling relating to plugins, and svg support, and allowing installation of non-listed plugins (currently broken functionality in 4.0)

**Comment by dkulp** [comment]
With 4.0, we specifically went through many of the installed packages and removed anything that is not needed by the FPP core to keep the image smaller.   The expectation is that plugins can and should install whatever additional functionality they may need.   This is done in many of the plugins that require installing USB development libraries, time code libraries, etc... that they need.     Adding an additional 50-70 MB of stuff that is not needed by FPP is no something we're likely to do at this point.  

Regarding the second point:  I just tried installing an unlisted plugin and it worked so I'm not sure what the issue is there.   If you can provide a reproducible case (or pull request) we could look at that.   That likely should be a separate issue report though.
