### ISSUE TITLE
Callback for after media has started

### ISSUE THREAD

**Issue by networx** [FalconChristmas/fpp#772]
We are working on a web app that plays the audio through web audio API with an audio buffer and are trying to synchronize it to the falcon playback. 

We have a plugin with a media callback that gets called. Then we get the microtime it was called and save it. Then when someone loads the web app we use that microtime to set the offset of when the audio file should play. We noticed the media callback gets called and then the media actually starts playing about 400ms after the callback is called. We have hard-coded this offset and it actually works well.

But it would be better for our use-case if there was a callback that happened after the media actually has started playing that includes the microtime that the audio started. Would it be possible to have a callback added that runs after the media is playing instead of before it starts? 

Thanks!

**Comment by dkulp** [comment]
For this type of thing, you may want to consider requiring FPP to run in "master" mode and registering a MultiSyncPlugin (see MultiSync.h).    You would then get periodic callbacks of the exact location in the media where FPP is so you can re-sync if you need to.  Since what you are doing is essentially syncing with. FPP, having FPP in master mode kind of makes sense.

**Comment by networx** [comment]
Great. I'll try that.

**Comment by ghormann** [comment]
Assuming the plugin worked. Closing.
