### ISSUE TITLE
Display Testing Auto-calculation on Start and End channels appears to be broken when your first channel is not 1

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#786]
This problem was observed in the Zoom room last night and I can confirm it this morning.

Steps to Reproduce:
Go to Channel Outputs -> LED Panels
Create a Matrix (3x3 P5s) 
Set start channel to 1. FPP UI will calculate total channels and Pixels (18432 pixels and 55296 channels)
Go to Display Testing
The Start Channel is 1 and the end channel is 55296. FPP correctly setup the "default" channels in that display.

Now go back to Channel Outputs -> LED Panels and change the start Channel to 1000.
Now go to Display Testing.
Start Channel in Display testing is set to 993 (it should be 1000)
End Channel in Display testing is set to 56296 (correct)

2nd test
go back to Channel Outputs -> LED Panels and change the start Channel to 2000.
Now go to Display Testing.
Start Channel in Display testing is set to 1993 (it should be 1000)
End Channel in Display testing is set to 57296 (correct)

Why is the start channel 7 channels lower?

![image](https://user-images.githubusercontent.com/8147459/91436479-d3a1f380-e82d-11ea-8834-aa37405e3781.png)
![image](https://user-images.githubusercontent.com/8147459/91436464-cab12200-e82d-11ea-93f8-f19f8150e95a.png)

![image](https://user-images.githubusercontent.com/8147459/91436505-e0264c00-e82d-11ea-9eeb-7847f1f30e32.png)
![image](https://user-images.githubusercontent.com/8147459/91436524-e74d5a00-e82d-11ea-8132-fa81f65fe379.png)

**Comment by triggerx** [comment]
My display testing channels appear to be wrong even when the start channel is 1.  I have a single string, 100 pixels.  Set up for channels 1-300.... When I go to Channel Testing, and select that Model, the start channel is 1 and the end channel is 348.  Running FPP v4.1.  Git Version 71390f3.

**Comment by cpinkham** [comment]
Internal channel numbers start at 0 but are shown in the UI as starting at 1.  The channel range for a FPP system is rounded down to the nearest interval of 8 so that storage reads are better aligned for performance reasons.  This is why you see a start channel on the test screen that doesn't align with the start channel of your only channel output.  I can see how this would throw off carefully planned RGB channel placement though, so there may be opportunity for improvement in the autoset of the start channel on the test screen.  The channel range calculated also takes into account all outputs, models, and event control channels, so it may be higher than expected.

If you select a specific model from the model dropdown on the channel test page, then you should get the exact start/end channels for that model without the "round down to the nearest interval of 8" manipulation.

I think this issue can be closed, we haven't tried to guarantee that the RGB colors as indicated on the channel test page align with the user's actual pixels RGB colors.

If this doesn't make sense or I'm missing something, we can reopen and revisit.
