### ISSUE TITLE
enhancement: Image: Playlist / Random

### ISSUE THREAD

**Issue by LightsOnHudson** [FalconChristmas/fpp#801]
Allow Random Images to be used in a Playlist like Media Random and output to a Pixel Overlay model.

**Comment by cpinkham** [comment]
You can use random images by specifying a directory name instead of an image filename.  This is my main use of the feature, since I created this playlist entry type to allow FPP to function as a digital photo frame.  FPP will remember which images it has displayed each time through the playlist and will reload the list once it has displayed all images.  So, if you add new images to the directory while the playlist is playing, they won't be picked up and possibly displayed until all existing images have been displayed.

**Comment by cpinkham** [comment]
The new File Chooser lets you choose individual images, but you can also type in a directory name to display images from the directory in a random order.  I would like to add file globbing at some point, but for now, enter "/home/fpp/media/images" and it will display random images.  There are a few more things we wanted to add to the pixel overlay code to support image display and other features, so the pixel overlay display of images may be a while.

**Comment by cpinkham** [comment]
Closing as the pixel overlay piece is addressed in request #800
