### ISSUE TITLE
Setting a password that starts with $$ causes you not to be able to login to FPP anymore.

### ISSUE THREAD

**Issue by MrSmoofy** [FalconChristmas/fpp#840]
# Please answer the following:
**FPP Version and Hardware**: 
FPP 4.2 running on Pi 4

**Describe the bug and Steps to reproduce**: 
1. Go to where you set the UI password
2. Enable UI Password
3. Enter admin/falcon when prompted
4. Change Password to something like $$U7rul8P$$
5. When prompted to enter admin/$$U7rul8P$$ it doesn't work, no password works you must reflash

**Expected behavior**: 
Expected to be able to use my password I entered

**Comment by darylc** [comment]
Can you confirm if the same problem occurs when using a password without special characters such as $ please?

**Comment by MrSmoofy** [comment]
The default password "falcon" works fine
The password "Y7dsas8C" works fine
The password "123456" works fine
The password "123456$$" did not work and now I am reflashing

**Comment by ghormann** [comment]
I would suspect this part of the code in settings.php (but have not confirmed it).   Because it is using a shell, and the value field is not escaped, my hunch is that $$ is being treated as a variable which expands to the PID of the shell.  

```
    shell_exec("sudo htpasswd -cbd " . $settings['mediaDirectory'] . "/config/.htpasswd admin " . $value);
    shell_exec("sudo htpasswd -bd " . $settings['mediaDirectory'] . "/config/.htpasswd fpp " . $value);
```
Example: 
![image](https://user-images.githubusercontent.com/24968726/96857824-768d7d00-142d-11eb-8e30-5b4513c50b50.png)

I can look into this in more detail on Saturday unless someone fixes it first. :-)

**Comment by MrSmoofy** [comment]
While I've not done any PHP programming myself, 20+ years of development experience would agree with that is what the issue probably is.

**Comment by darylc** [comment]
FPP's original developer passed a lot of user data to the command line like what is happening here.  Some of them have been fixed as bugs have been reported, but if you have the energy feel free to help out the project by doing a more thorough review and submitting pull requests.

Else avoid special characters in your password for now and hope that one of the developers gets motivated to fix this occurrence at some point.

**Comment by ghormann** [comment]
This should be resolved now.
1) No longer user shell for writing password file so no problems with escaping special characters
2) New passwords will use BCRYPT but existing crypt passwords still work. -- (Apache 2.4 supports both but recomends BCRYPT).
3) the .htpasswd file is now owned by fpp instead of root.  (I'm unclear why the sudo was used before, but in my testing this wasn't necessary.   Making it owned by fpp makes it much easier to write the file via fpp. 

I did the following unit testing before publishing: 
1) Able to change old password (CRYPT, owned by root) to new password with BCRYPT (owned by fpp)
2) Passwords with $$$ supported
3) Able to create new password if no password exists via UI.
4) Able to remove password via UI.

**Comment by MrSmoofy** [comment]
Thanks @ghormann
