### ISSUE TITLE
Proxy linked page not displaying full webpage of e682 controller

### ISSUE THREAD

**Issue by raydorman** [FalconChristmas/fpp#849]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 

FPP v4.3-5-g97c142a9 on a Pi 3
Controller is SanDevice e682 on 4.081 firmware

**Describe the bug and Steps to reproduce**: 
1. Status Controls -> Proxy Settings
2. Enter in IP address of SanDevice e682controller
3. Click on link to open webpage config page of controller
4. Webpage does not display full page, truncated at the bottom

**Expected behavior**: 
Full config webpage should be displayed
Works as expected when connected directly to controller card from PC with network cable

Screenshot and logs attached

Thanks!

**Additional Attachments**
Please include the log files. To create the file:

**Comment by raydorman** [comment]
![screenshot](https://user-images.githubusercontent.com/2031011/97472632-68a19580-1920-11eb-943a-ea19d31df07c.png)

**Comment by raydorman** [comment]
[FPP_Logs_20201028.1719.zip](https://github.com/FalconChristmas/fpp/files/5453727/FPP_Logs_20201028.1719.zip)

**Comment by dkulp** [comment]
This is a problem with the e68x firmware that they know about.   It's not returning a proper HTTP 1.x response (no HTTP headers at all) and thus the Apache reverse proxy has no idea what the response is or the size or anything and thus will only return part of the page.   This was supposed to be fixed in the 5.x firmware this summer, but apparently has been delayed.

**Comment by raydorman** [comment]
Ah, that makes sense! Thanks so much.

**Comment by ghormann** [comment]
Closing as not FPP related
