### ISSUE TITLE
Scheduler should publish MQTT topic a configurable number of seconds before starting playlist or going idle

### ISSUE THREAD

**Issue by jasonspo** [FalconChristmas/fpp#882]
Hello, I would like FPP to publish MQTT messages so that I may automate outdoor house and landscape lighting based on whether a FPP show is running.  After a start and graceful stop of a show I would like the option to publish these "show running"/ "show stopped" messages to trigger other automations and routines.

Also, an optional MQTT publish xx seconds before show start and before graceful stop to trigger other preparation events, such as begin ramping up exterior lighting as the end of show or lead-out plays.

Thanks!

**Comment by ghormann** [comment]
@jasonspo 
As for if a show is running or not, can't you just use the existing playlist_details message? On the MQTT settings page if you set the publish frequence to 2 seconds you get this topic published telling you what playlist is currently playing or "Idle" if there is none.  There is also /playlist/name/status which just publishes when the play list changes. (will be null if idle.).   More documentation on these two topics is at https://raw.githubusercontent.com/FalconChristmas/fpp/master/docs/MQTT.txt   I prefer the playlist_details because it better handles if a single message gets lost for some reason.

![image](https://user-images.githubusercontent.com/24968726/100473097-93ac1000-30ab-11eb-8909-58e1af92b2ff.png)

As for your second request, that would be an enhancement. I'll change the title of this to reflect that request.

**Comment by jasonspo** [comment]
@ghormann 
I will test your playlist recommendation for my show running status...thanks.

Regarding the second request, that would be very useful to me if that is possible in some future release.  To clarify your topic change, I would be requesting both before show start and before show stop.

**Comment by cpinkham** [comment]
It is hard to do this before the playlist stops because there are so many variables.  We only know the actual stop time if a hard stop is used.  If a graceful stop is used, then we would have to look at the media and sequence playing and check the length of those to calculate an accurate stop time.  This could also be affected by the LeadOut, so the calculation could get more complicated.

FPP v5.0 will have the ability to trigger a FPP Command when a playlist starts and stops as well as on a sort of countdown T-Minus schedule before a playlist starts.  Right now the code will allow FPP Commands to be set for 1, 2, 3, 4, 5, 10, 20, 30, 60, 120, 300, or 600 seconds before a playlist starts.  These will be part of the new Command Presets code which will be committed shortly.  When I commit that I will reference/close this ticket since I don't think we will be adding the "before idle" portion due to the variations involved.  The new code does trigger a Command Preset when the playlist transitions from running to stopping gracefully, stopping after loop, or stopping now.  These may be useful for what you are trying to achieve or you can use the PLAYLIST_STOPPED Command Preset to run a FPP Command when the playlist actually stops.
