### ISSUE TITLE
Script Privilages

### ISSUE THREAD

**Issue by MacGuyverism** [FalconChristmas/fpp#928]
Version Info:
FPP Version: | v4.3
Platform: | Raspberry Pi (Pi 3 Model B)
FPP OS Build: | v4.3
OS Version: | Raspbian GNU/Linux 10 (buster)
[FPP_Logs_20201216.0119.zip](https://github.com/FalconChristmas/fpp/files/5699683/FPP_Logs_20201216.0119.zip)

I just set up a tune to sign, and decided to run a start effect looping script at the lead in of the playlist, and a stop effect in the lead out. However when I ran the script, I got an error:

ERROR: Unknown file extension: Start_Tune_To on /home/fpp/media/scripts/Start_Tune_To

It turns out the Start_Tune_To.sh file didn’t have exec privilege’s.  
The solution was a chmod +x Start_Tune_To.sh from the ssh terminal.  

Maybe FPP should do this automatically when trying to run scripts?

**Comment by cpinkham** [comment]
FPP scripts don't need to be executable because they are called with a wrapper script that calls the correct shell interpreter.  We did this partially because some users were using FAT-based USB sticks for storage which didn't have an execute bit.

Scripts are called like this:

/opt/fpp/scripts/eventScript /home/fpp/media/scripts/Start_Tune_To.sh

The eventScript wrapper sees the .sh extension and in turn calls this:

exec /bin/bash /home/fpp/media/scripts/Start_Tune_To.sh

We also use the wrapper to setup the environment variables for scripts so that they have access to more information about FPP.

The filename in the log entry is telling us that you first uploaded without the .sh extension on the file, then you reuploaded or renamed the file to have a .sh extension.  That was what fixed the issue, not the chmod.
