### ISSUE TITLE
FPP UI sometimes shows Not Found for files which exist but have an issue with ffprobe parsing metadata.

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#940]
FPP will show 'Not Found' in the UI for video files which ffprobe can not properly probe the metadata and return the data in a JSON string.  It would be good if we could detect this probe failure and not show "Not Found" in the UI, but instead show some other error message indicating that the metadata can not be parsed properly.

**Comment by cpinkham** [comment]
3c81749038a fixed a similar issue for .fseq files.

**Comment by darylc** [comment]
do we have any example files to work on this with?

**Comment by darylc** [comment]
I uploaded a bunch of random video files from various sources and I cannot replicate this so I'm going to close this out.   Some files showed unknown length as escapeshellarg was removing characters before being passed to ffprobe, this was fixed by adding setlocale(LC_CTYPE, "en_US.UTF-8") to config.php
