### ISSUE TITLE
MQTT not working on MASTER BRANCH

### ISSUE THREAD

**Issue by TechTurtleTube** [FalconChristmas/fpp#955]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
Example: *FPP 4.2 running on BBB*

 ****v4.x-master-837-gbd223f8b (master branch)****

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
**mqtt will not accept play stop or etc.. commands from home assistant .. however the home assistant plug in still works. also, the info is coming trough its like the endpoint changed for some commands **

**Expected behavior**: 
A clear and concise description of what you expected to happen and why.
**mqtt does nothing when i try to play a playlist or stop a play list via mqtt command** 

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.
[FPP_Logs_20210126.1945.zip](https://github.com/FalconChristmas/fpp/files/5875731/FPP_Logs_20210126.1945.zip)

![Screenshot 2021-01-26 004430](https://user-images.githubusercontent.com/54298835/105897508-4209fe00-5fe6-11eb-8868-9af9cdc42a94.jpg)
![Screenshot 2021-01-26 004556](https://user-images.githubusercontent.com/54298835/105897524-47ffdf00-5fe6-11eb-8392-113b81ed8ad4.jpg)
![Screenshot 2021-01-26 004923](https://user-images.githubusercontent.com/54298835/105897554-52ba7400-5fe6-11eb-9a5d-3ce829457c44.jpg)

**Comment by ghormann** [comment]
I was able to reproduce this on my one of my Dev boxes.  

![image](https://user-images.githubusercontent.com/24968726/105927256-a1c9ce80-6011-11eb-9c01-b808fd5916e0.png)

I'll spend some more timing trying to get to root cause.

**Comment by ghormann** [comment]
@cpinkham  Looks like this was introduced with the new Player Class.  From what I can tell, the Player is being created extremely early in the startup process, even before MQTT because it is a singleton.   Because the Player Class creates the Playlist in the constructor, the check if MQTT is enabled inside of Playlist() fails and no callback is registered.    

How would you like to handle this?

**Comment by cpinkham** [comment]
@ghormann I'm thinking that for now, we add a Player::Init() method and call it in fppd.c in main() before MainLoop() is called.  Eventually, the Playlist instance would be created and destroyed on the fly by the Player, but for now since there is only a single Playlist possible, it should be OK to move the "playlist = new Playlist() call from Player::Player() to a new Player::Init().  If you want to test and commit that, I'm fine with it, otherwise I can try to get a fix in on Thursday or Friday.

I just took another look at the code and that MQTT callback logic in Playlist::Playlist() will have to get moved to the Player at some point as well as part of all the other changes to support multiple concurrent playlists.

**Comment by ghormann** [comment]
Thanks @cpinkham.
