### ISSUE TITLE
Randomized Playlist options

### ISSUE THREAD

**Issue by Poporacer** [FalconChristmas/fpp#984]
**Is your feature request related to a problem? Please describe.**
If you select the "Once Per Load" option of the Randomize function, there is a possibility that you could get the same song playing back to back if the last random item of the first list is the same as the first random item in the second list.

**Describe the solution you'd like**
If the first item in the newly generated random list is the same as the last item in the previous list, either regenerate the Random order (which would require another comparison) or just move the first item in the list a spot or two down the list

**Describe alternatives you've considered**

**Additional context**

**Comment by jnovack** [comment]
The safest (with minimal calculations) is to insert the duped song to spot `s = floor((n/2)+1)` (where `n` is the number of list items).

* If `n == 1`, then `s = 1`.
* If `n == 2`, then `s = 2`.
* If `n == 3`, then `s = 2`.
* If `n == 4`, then `s = 3`.

We can attempt to idiot-proof this option by only enabling it on playlists with 2 or more entries.

**Comment by cpinkham** [comment]
I think the easiest solution in the while loop in Playlist::RandomizeMainPlaylist() is to just check if m_mainPlaylist is empty and the playlist size is > 1 and if so we do a while loop while p == (m_mainPlaylist.size() - 1).  If p isn't the last entry then we only call std::rand() once, otherwise we'd keep calling it until p was not equal to the last entry.  Testing the code will take longer than actually modifying it, but I'll try to take a look some time.
